use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        // Widen the `memory_jobs.kind` CHECK to admit the `reprocess` job
        // (epic 0011 ticket 0010 — the correction engine). Builds on
        // `m20000000_000007`'s set ('embed', 'extract', 'categorize').
        // Postgres has no ALTER ... MODIFY CHECK, so drop and recreate; the
        // constraint name is Postgres's autogenerated `<table>_<column>_check`.
        db.execute_unprepared("ALTER TABLE memory_jobs DROP CONSTRAINT memory_jobs_kind_check")
            .await?;
        db.execute_unprepared(
            "ALTER TABLE memory_jobs
                ADD CONSTRAINT memory_jobs_kind_check
                CHECK (kind IN ('embed', 'extract', 'categorize', 'reprocess'))",
        )
        .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();
        db.execute_unprepared("ALTER TABLE memory_jobs DROP CONSTRAINT memory_jobs_kind_check")
            .await?;
        db.execute_unprepared(
            "ALTER TABLE memory_jobs
                ADD CONSTRAINT memory_jobs_kind_check
                CHECK (kind IN ('embed', 'extract', 'categorize'))",
        )
        .await?;
        Ok(())
    }
}

// Rust guideline compliant 2026-02-21
