//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_tools")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub agent_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tool_id: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    #[sea_orm(
        belongs_to,
        from = "agent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agents: HasOne<super::agents::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tool_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tools: HasOne<super::tools::Entity>,
}
