//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "agent_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_agent_users_agent_user_unique")]
    pub agent_id: i64,
    #[sea_orm(unique_key = "idx_agent_users_agent_user_unique")]
    pub user_id: String,
    pub permissions: i16,
    pub shared_by: String,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "agent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub agents: HasOne<super::agents::Entity>,
}
