//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: String,
    pub user_id: String,
    pub organization_pid: String,
    pub agent_id: i64,
    pub title: Option<String>,
    pub message_count: i32,
    pub last_message_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub is_deleted: bool,
    #[sea_orm(
        belongs_to,
        from = "agent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub agents: HasOne<super::agents::Entity>,
    #[sea_orm(has_many)]
    pub conversation_documents: HasMany<super::conversation_documents::Entity>,
    #[sea_orm(has_many)]
    pub conversation_users: HasMany<super::conversation_users::Entity>,
    #[sea_orm(has_many)]
    pub messages: HasMany<super::messages::Entity>,
}
