//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "provider_rates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_provider_rates_unique")]
    pub provider_id: i64,
    #[sea_orm(unique_key = "idx_provider_rates_unique")]
    pub limit_type: String,
    pub limit_value: i32,
    pub window_seconds: i32,
    #[sea_orm(
        belongs_to,
        from = "provider_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub providers: HasOne<super::providers::Entity>,
}
