//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tool_secrets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tool_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub secret_id: i64,
    #[sea_orm(
        belongs_to,
        from = "secret_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub secrets: HasOne<super::secrets::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tool_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tools: HasOne<super::tools::Entity>,
}
