//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tools")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: String,
    #[sea_orm(unique)]
    pub name: String,
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub tool_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub parameters_schema: Json,
    pub is_active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many, via = "agent_tools")]
    pub agents: HasMany<super::agents::Entity>,
    #[sea_orm(has_many, via = "tool_secrets")]
    pub secrets: HasMany<super::secrets::Entity>,
}
