{{- if and .Values.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "service.secretName" . }}
    creationPolicy: Owner
  {{- if .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- range .Values.externalSecret.dataFrom }}
    - extract:
        key: {{ .extract.key }}
        {{- if .extract.version }}
        version: {{ .extract.version | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.externalSecret.data }}
  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version | quote }}
        {{- end }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
