[tools]
node = "latest"
buf = "latest"

terraform = "latest"
helm = "latest"
kind = "latest"
kubectl = "latest"
protoc = "latest"
argocd = "latest"

[env]
DB_HOST = "localhost"
DB_PORT = "54321"
DB_USER = "postgres"
DB_PASS = "postgres"

[settings]
idiomatic_version_file_enable_tools = []
