// @generated
// This file is @generated by prost-build.
// ============================================================================
// Channel types
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Channel {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="ChannelType", tag="3")]
    pub channel_type: i32,
    #[prost(string, optional, tag="4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub organization_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="7")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelSummary {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="ChannelType", tag="3")]
    pub channel_type: i32,
    #[prost(bool, tag="4")]
    pub has_unread: bool,
    #[prost(int32, tag="5")]
    pub unread_count: i32,
    #[prost(message, optional, tag="6")]
    pub last_message: ::core::option::Option<ChatMessage>,
    #[prost(string, optional, tag="7")]
    pub last_read_at: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelMember {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ChannelRole", tag="4")]
    pub role: i32,
    #[prost(string, tag="5")]
    pub joined_at: ::prost::alloc::string::String,
}
// ============================================================================
// Message types
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatMessage {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub sender_name: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub content: ::prost::alloc::string::String,
    /// Thread parent
    #[prost(string, optional, tag="7")]
    pub parent_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="8")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(bool, tag="9")]
    pub is_deleted: bool,
    #[prost(bool, tag="10")]
    pub is_edited: bool,
    #[prost(string, optional, tag="11")]
    pub edited_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="12")]
    pub reactions: ::prost::alloc::vec::Vec<Reaction>,
    #[prost(message, repeated, tag="13")]
    pub attachments: ::prost::alloc::vec::Vec<Attachment>,
    #[prost(message, repeated, tag="14")]
    pub mentions: ::prost::alloc::vec::Vec<Mention>,
    /// Thread reply count
    #[prost(int32, optional, tag="15")]
    pub reply_count: ::core::option::Option<i32>,
    #[prost(bool, tag="16")]
    pub is_pinned: bool,
    #[prost(oneof="chat_message::Sender", tags="3, 4")]
    pub sender: ::core::option::Option<chat_message::Sender>,
}
/// Nested message and enum types in `ChatMessage`.
pub mod chat_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Sender {
        #[prost(message, tag="3")]
        User(super::UserSender),
        #[prost(message, tag="4")]
        Agent(super::AgentSender),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserSender {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentSender {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub agent_slug: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reaction {
    #[prost(string, tag="1")]
    pub emoji: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub count: i32,
    /// Who reacted (for UI)
    #[prost(string, repeated, tag="3")]
    pub user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag="4")]
    pub includes_me: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Attachment {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub size_bytes: i64,
    #[prost(string, tag="5")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, optional, tag="6")]
    pub thumbnail_url: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mention {
    #[prost(enumeration="MentionType", tag="1")]
    pub mention_type: i32,
    /// user_id, channel_pid, or role name
    #[prost(string, tag="2")]
    pub target_id: ::prost::alloc::string::String,
    /// @username, #channel, @role
    #[prost(string, tag="3")]
    pub display_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemNotification {
    #[prost(enumeration="SystemNotificationType", tag="1")]
    pub kind: i32,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="3")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ============================================================================
// Enums
// ============================================================================

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChannelType {
    Unspecified = 0,
    /// Open to all authenticated users
    Global = 1,
    /// Tied to an organization
    Organization = 2,
    /// DM or group DM
    Private = 3,
    /// System notifications
    System = 4,
}
impl ChannelType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHANNEL_TYPE_UNSPECIFIED",
            Self::Global => "CHANNEL_TYPE_GLOBAL",
            Self::Organization => "CHANNEL_TYPE_ORGANIZATION",
            Self::Private => "CHANNEL_TYPE_PRIVATE",
            Self::System => "CHANNEL_TYPE_SYSTEM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHANNEL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHANNEL_TYPE_GLOBAL" => Some(Self::Global),
            "CHANNEL_TYPE_ORGANIZATION" => Some(Self::Organization),
            "CHANNEL_TYPE_PRIVATE" => Some(Self::Private),
            "CHANNEL_TYPE_SYSTEM" => Some(Self::System),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChannelRole {
    Unspecified = 0,
    Member = 1,
    Moderator = 2,
    Admin = 3,
    Owner = 4,
}
impl ChannelRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHANNEL_ROLE_UNSPECIFIED",
            Self::Member => "CHANNEL_ROLE_MEMBER",
            Self::Moderator => "CHANNEL_ROLE_MODERATOR",
            Self::Admin => "CHANNEL_ROLE_ADMIN",
            Self::Owner => "CHANNEL_ROLE_OWNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHANNEL_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "CHANNEL_ROLE_MEMBER" => Some(Self::Member),
            "CHANNEL_ROLE_MODERATOR" => Some(Self::Moderator),
            "CHANNEL_ROLE_ADMIN" => Some(Self::Admin),
            "CHANNEL_ROLE_OWNER" => Some(Self::Owner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PresenceStatus {
    Unspecified = 0,
    Online = 1,
    Away = 2,
    /// Do not disturb
    Dnd = 3,
    Offline = 4,
}
impl PresenceStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRESENCE_STATUS_UNSPECIFIED",
            Self::Online => "PRESENCE_STATUS_ONLINE",
            Self::Away => "PRESENCE_STATUS_AWAY",
            Self::Dnd => "PRESENCE_STATUS_DND",
            Self::Offline => "PRESENCE_STATUS_OFFLINE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRESENCE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "PRESENCE_STATUS_ONLINE" => Some(Self::Online),
            "PRESENCE_STATUS_AWAY" => Some(Self::Away),
            "PRESENCE_STATUS_DND" => Some(Self::Dnd),
            "PRESENCE_STATUS_OFFLINE" => Some(Self::Offline),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MentionType {
    Unspecified = 0,
    User = 1,
    Channel = 2,
    Role = 3,
    Everyone = 4,
    Here = 5,
}
impl MentionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MENTION_TYPE_UNSPECIFIED",
            Self::User => "MENTION_TYPE_USER",
            Self::Channel => "MENTION_TYPE_CHANNEL",
            Self::Role => "MENTION_TYPE_ROLE",
            Self::Everyone => "MENTION_TYPE_EVERYONE",
            Self::Here => "MENTION_TYPE_HERE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MENTION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MENTION_TYPE_USER" => Some(Self::User),
            "MENTION_TYPE_CHANNEL" => Some(Self::Channel),
            "MENTION_TYPE_ROLE" => Some(Self::Role),
            "MENTION_TYPE_EVERYONE" => Some(Self::Everyone),
            "MENTION_TYPE_HERE" => Some(Self::Here),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SystemNotificationType {
    Unspecified = 0,
    Info = 1,
    Warning = 2,
    Error = 3,
    Maintenance = 4,
}
impl SystemNotificationType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SYSTEM_NOTIFICATION_TYPE_UNSPECIFIED",
            Self::Info => "SYSTEM_NOTIFICATION_TYPE_INFO",
            Self::Warning => "SYSTEM_NOTIFICATION_TYPE_WARNING",
            Self::Error => "SYSTEM_NOTIFICATION_TYPE_ERROR",
            Self::Maintenance => "SYSTEM_NOTIFICATION_TYPE_MAINTENANCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SYSTEM_NOTIFICATION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "SYSTEM_NOTIFICATION_TYPE_INFO" => Some(Self::Info),
            "SYSTEM_NOTIFICATION_TYPE_WARNING" => Some(Self::Warning),
            "SYSTEM_NOTIFICATION_TYPE_ERROR" => Some(Self::Error),
            "SYSTEM_NOTIFICATION_TYPE_MAINTENANCE" => Some(Self::Maintenance),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReportReason {
    Unspecified = 0,
    Spam = 1,
    Harassment = 2,
    HateSpeech = 3,
    Violence = 4,
    Nsfw = 5,
    Misinformation = 6,
    Other = 7,
}
impl ReportReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REPORT_REASON_UNSPECIFIED",
            Self::Spam => "REPORT_REASON_SPAM",
            Self::Harassment => "REPORT_REASON_HARASSMENT",
            Self::HateSpeech => "REPORT_REASON_HATE_SPEECH",
            Self::Violence => "REPORT_REASON_VIOLENCE",
            Self::Nsfw => "REPORT_REASON_NSFW",
            Self::Misinformation => "REPORT_REASON_MISINFORMATION",
            Self::Other => "REPORT_REASON_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REPORT_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "REPORT_REASON_SPAM" => Some(Self::Spam),
            "REPORT_REASON_HARASSMENT" => Some(Self::Harassment),
            "REPORT_REASON_HATE_SPEECH" => Some(Self::HateSpeech),
            "REPORT_REASON_VIOLENCE" => Some(Self::Violence),
            "REPORT_REASON_NSFW" => Some(Self::Nsfw),
            "REPORT_REASON_MISINFORMATION" => Some(Self::Misinformation),
            "REPORT_REASON_OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
// ============================================================================
// Channel CRUD
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetChannelsRequest {
    #[prost(enumeration="ChannelType", optional, tag="1")]
    pub channel_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag="2")]
    pub organization_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="3")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="4")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="5")]
    pub include_archived: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetChannelsResponse {
    #[prost(message, repeated, tag="1")]
    pub channels: ::prost::alloc::vec::Vec<ChannelSummary>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateChannelRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="ChannelType", tag="2")]
    pub channel_type: i32,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub organization_pid: ::core::option::Option<::prost::alloc::string::String>,
    /// For private channels / group DMs
    #[prost(string, repeated, tag="5")]
    pub participant_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateChannelResponse {
    #[prost(message, optional, tag="1")]
    pub channel: ::core::option::Option<Channel>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetChannelRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetChannelResponse {
    #[prost(message, optional, tag="1")]
    pub channel: ::core::option::Option<Channel>,
    /// Current user's membership info
    #[prost(message, optional, tag="2")]
    pub my_membership: ::core::option::Option<ChannelMember>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateChannelRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="5")]
    pub archived: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateChannelResponse {
    #[prost(message, optional, tag="1")]
    pub channel: ::core::option::Option<Channel>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteChannelRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteChannelResponse {
}
// ============================================================================
// Membership
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteToChannelRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub invite_message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InviteToChannelResponse {
    #[prost(message, repeated, tag="1")]
    pub results: ::prost::alloc::vec::Vec<InviteResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteResult {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub success: bool,
    /// e.g., "user_not_found", "already_member", "blocked"
    #[prost(string, optional, tag="3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LeaveChannelRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LeaveChannelResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KickFromChannelRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KickFromChannelResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetChannelMembersRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="2")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ChannelRole", optional, tag="4")]
    pub role_filter: ::core::option::Option<i32>,
    #[prost(bool, optional, tag="5")]
    pub online_only: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetChannelMembersResponse {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<ChannelMember>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub total_count: i32,
    #[prost(int32, tag="4")]
    pub online_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateMemberRoleRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration="ChannelRole", tag="3")]
    pub new_role: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateMemberRoleResponse {
    #[prost(message, optional, tag="1")]
    pub member: ::core::option::Option<ChannelMember>,
}
// ============================================================================
// Read state
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAsReadRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    /// If absent, mark all as read
    #[prost(string, optional, tag="2")]
    pub last_read_message_pid: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAsReadResponse {
    #[prost(string, tag="1")]
    pub last_read_at: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub remaining_unread: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUnreadCountsRequest {
    /// If empty, get all channels
    #[prost(string, repeated, tag="1")]
    pub channel_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUnreadCountsResponse {
    #[prost(map="string, message", tag="1")]
    pub channels: ::std::collections::HashMap<::prost::alloc::string::String, UnreadInfo>,
    #[prost(int32, tag="2")]
    pub total_unread: i32,
    #[prost(int32, tag="3")]
    pub total_mentions: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnreadInfo {
    #[prost(int32, tag="1")]
    pub unread_count: i32,
    #[prost(int32, tag="2")]
    pub mention_count: i32,
    #[prost(string, optional, tag="3")]
    pub last_message_at: ::core::option::Option<::prost::alloc::string::String>,
}
// ============================================================================
// DMs / Conversations
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartConversationRequest {
    /// Other users (self is implicit)
    #[prost(string, repeated, tag="1")]
    pub participant_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional first message
    #[prost(string, optional, tag="2")]
    pub initial_message: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartConversationResponse {
    #[prost(message, optional, tag="1")]
    pub channel: ::core::option::Option<Channel>,
    /// true if new channel, false if existing
    #[prost(bool, tag="2")]
    pub created: bool,
    /// If initial_message was sent
    #[prost(string, optional, tag="3")]
    pub initial_message_pid: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConversationsRequest {
    #[prost(int32, optional, tag="1")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="3")]
    pub unread_only: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsResponse {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<ConversationSummary>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationSummary {
    #[prost(message, optional, tag="1")]
    pub channel: ::core::option::Option<Channel>,
    /// Other participants (not self)
    #[prost(message, repeated, tag="2")]
    pub participants: ::prost::alloc::vec::Vec<ParticipantInfo>,
    #[prost(message, optional, tag="3")]
    pub last_message: ::core::option::Option<ChatMessage>,
    #[prost(int32, tag="4")]
    pub unread_count: i32,
    #[prost(string, optional, tag="5")]
    pub last_read_at: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParticipantInfo {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="PresenceStatus", tag="4")]
    pub presence: i32,
}
// ============================================================================
// Stream (bidirectional real-time connection)
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientEvent {
    #[prost(oneof="client_event::Event", tags="1, 2, 3, 4")]
    pub event: ::core::option::Option<client_event::Event>,
}
/// Nested message and enum types in `ClientEvent`.
pub mod client_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="1")]
        Subscribe(super::SubscribeChannel),
        #[prost(message, tag="2")]
        Unsubscribe(super::UnsubscribeChannel),
        #[prost(message, tag="3")]
        Typing(super::TypingIndicator),
        #[prost(message, tag="4")]
        Presence(super::PresenceUpdate),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeChannel {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsubscribeChannel {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypingIndicator {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub is_typing: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PresenceUpdate {
    #[prost(enumeration="PresenceStatus", tag="1")]
    pub status: i32,
    #[prost(string, optional, tag="2")]
    pub status_text: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEvent {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(oneof="server_event::Event", tags="2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15")]
    pub event: ::core::option::Option<server_event::Event>,
}
/// Nested message and enum types in `ServerEvent`.
pub mod server_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="2")]
        Message(super::ChatMessage),
        #[prost(message, tag="3")]
        MessageEdited(super::MessageEdited),
        #[prost(message, tag="4")]
        MessageDeleted(super::MessageDeleted),
        #[prost(message, tag="5")]
        ReactionAdded(super::ReactionAdded),
        #[prost(message, tag="6")]
        ReactionRemoved(super::ReactionRemoved),
        #[prost(message, tag="7")]
        UserTyping(super::UserTyping),
        #[prost(message, tag="8")]
        UserPresence(super::UserPresence),
        #[prost(message, tag="9")]
        UserJoined(super::UserJoinedChannel),
        #[prost(message, tag="10")]
        UserLeft(super::UserLeftChannel),
        #[prost(message, tag="11")]
        ChannelUpdated(super::ChannelUpdated),
        #[prost(message, tag="12")]
        Notification(super::SystemNotification),
        #[prost(message, tag="13")]
        MessagePinned(super::MessagePinned),
        #[prost(message, tag="14")]
        MessageUnpinned(super::MessageUnpinned),
        #[prost(message, tag="15")]
        AgentStreaming(super::AgentStreaming),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageEdited {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub new_content: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub edited_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageDeleted {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReactionAdded {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub emoji: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReactionRemoved {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub emoji: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserTyping {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_typing: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserPresence {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration="PresenceStatus", tag="2")]
    pub status: i32,
    #[prost(string, optional, tag="3")]
    pub status_text: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserJoinedChannel {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserLeftChannel {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChannelUpdated {
    #[prost(message, optional, tag="1")]
    pub channel: ::core::option::Option<Channel>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessagePinned {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub pinned_by_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageUnpinned {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
/// Agent streaming (for AI responses)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentStreaming {
    #[prost(string, tag="1")]
    pub agent_slug: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub done: bool,
    #[prost(string, tag="4")]
    pub message_pid: ::prost::alloc::string::String,
}
// ============================================================================
// Message operations
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub parent_pid: ::core::option::Option<::prost::alloc::string::String>,
    /// Pre-uploaded attachments
    #[prost(string, repeated, tag="4")]
    pub attachment_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageResponse {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub timestamp: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMessageHistoryRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub limit: i32,
    #[prost(string, optional, tag="3")]
    pub before_timestamp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub after_timestamp: ::core::option::Option<::prost::alloc::string::String>,
    /// For jumping to a message
    #[prost(string, optional, tag="5")]
    pub around_message_pid: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessageHistoryResponse {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    #[prost(bool, tag="2")]
    pub has_more_before: bool,
    #[prost(bool, tag="3")]
    pub has_more_after: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessageResponse {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<ChatMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EditMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub new_content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditMessageResponse {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<ChatMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageResponse {
}
// ============================================================================
// Reactions
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReactToMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub emoji: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReactToMessageResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveReactionRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub emoji: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveReactionResponse {
}
// ============================================================================
// Pins
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PinMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PinMessageResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnpinMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnpinMessageResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPinnedMessagesRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPinnedMessagesResponse {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
}
// ============================================================================
// Threads
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetThreadRequest {
    #[prost(string, tag="1")]
    pub parent_message_pid: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="2")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="3")]
    pub before_timestamp: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetThreadResponse {
    #[prost(message, optional, tag="1")]
    pub parent: ::core::option::Option<ChatMessage>,
    #[prost(message, repeated, tag="2")]
    pub replies: ::prost::alloc::vec::Vec<ChatMessage>,
    #[prost(bool, tag="3")]
    pub has_more: bool,
}
// ============================================================================
// Search
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchMessagesRequest {
    /// If absent, search all accessible
    #[prost(string, optional, tag="1")]
    pub channel_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="2")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub from_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub after_timestamp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub before_timestamp: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="6")]
    pub has_attachments: ::core::option::Option<bool>,
    #[prost(bool, optional, tag="7")]
    pub is_pinned: ::core::option::Option<bool>,
    #[prost(int32, tag="8")]
    pub limit: i32,
    #[prost(string, optional, tag="9")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMessagesResponse {
    #[prost(message, repeated, tag="1")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    #[prost(int32, tag="2")]
    pub total_count: i32,
    #[prost(string, optional, tag="3")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
// ============================================================================
// Reports
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportMessageRequest {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(enumeration="ReportReason", tag="2")]
    pub reason: i32,
    #[prost(string, optional, tag="3")]
    pub details: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportMessageResponse {
    #[prost(string, tag="1")]
    pub report_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportUserRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(enumeration="ReportReason", tag="3")]
    pub reason: i32,
    #[prost(string, optional, tag="4")]
    pub details: ::core::option::Option<::prost::alloc::string::String>,
    /// Message PIDs as evidence
    #[prost(string, repeated, tag="5")]
    pub evidence_message_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportUserResponse {
    #[prost(string, tag="1")]
    pub report_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetReportsRequest {
    /// Filter by channel
    #[prost(string, optional, tag="1")]
    pub channel_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ReportStatus", optional, tag="2")]
    pub status: ::core::option::Option<i32>,
    #[prost(enumeration="ReportReason", optional, tag="3")]
    pub reason: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="5")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReportsResponse {
    #[prost(message, repeated, tag="1")]
    pub reports: ::prost::alloc::vec::Vec<Report>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub total_pending: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Report {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(enumeration="ReportType", tag="2")]
    pub report_type: i32,
    #[prost(string, tag="3")]
    pub reporter_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub reporter_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub target_message_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub target_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="7")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(enumeration="ReportReason", tag="8")]
    pub reason: i32,
    #[prost(string, optional, tag="9")]
    pub details: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ReportStatus", tag="10")]
    pub status: i32,
    #[prost(string, tag="11")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, optional, tag="12")]
    pub resolved_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="13")]
    pub resolved_by_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="14")]
    pub resolution_notes: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ReportResolution", optional, tag="15")]
    pub resolution: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveReportRequest {
    #[prost(string, tag="1")]
    pub report_pid: ::prost::alloc::string::String,
    #[prost(enumeration="ReportResolution", tag="2")]
    pub resolution: i32,
    #[prost(string, optional, tag="3")]
    pub notes: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional action to take
    #[prost(message, optional, tag="4")]
    pub action: ::core::option::Option<ModerationAction>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModerationAction {
    #[prost(oneof="moderation_action::Action", tags="1, 2, 3, 4")]
    pub action: ::core::option::Option<moderation_action::Action>,
}
/// Nested message and enum types in `ModerationAction`.
pub mod moderation_action {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Action {
        #[prost(message, tag="1")]
        DeleteMessage(super::DeleteMessageAction),
        #[prost(message, tag="2")]
        MuteUser(super::MuteUserAction),
        #[prost(message, tag="3")]
        BanUser(super::BanUserAction),
        #[prost(message, tag="4")]
        WarnUser(super::WarnUserAction),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageAction {
    #[prost(string, tag="1")]
    pub message_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MuteUserAction {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int64, optional, tag="2")]
    pub duration_seconds: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BanUserAction {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, optional, tag="2")]
    pub delete_messages: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WarnUserAction {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub warning_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveReportResponse {
    #[prost(message, optional, tag="1")]
    pub report: ::core::option::Option<Report>,
}
// ============================================================================
// User restrictions
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MuteUserRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// If absent, permanent until unmuted
    #[prost(int64, optional, tag="3")]
    pub duration_seconds: ::core::option::Option<i64>,
    #[prost(string, optional, tag="4")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MuteUserResponse {
    /// empty if permanent
    #[prost(string, tag="1")]
    pub muted_until: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnmuteUserRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnmuteUserResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BanUserRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    /// Delete user's messages in channel
    #[prost(bool, optional, tag="4")]
    pub delete_messages: ::core::option::Option<bool>,
    /// How far back to delete (default: all)
    #[prost(int64, optional, tag="5")]
    pub delete_messages_seconds: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BanUserResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnbanUserRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnbanUserResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBannedUsersRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="2")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBannedUsersResponse {
    #[prost(message, repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<BannedUser>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BannedUser {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub banned_by_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub banned_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMutedUsersRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="2")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMutedUsersResponse {
    #[prost(message, repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<MutedUser>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MutedUser {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub muted_by_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub muted_at: ::prost::alloc::string::String,
    /// empty if permanent
    #[prost(string, tag="7")]
    pub muted_until: ::prost::alloc::string::String,
}
// ============================================================================
// Moderation log
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModerationLogRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    /// Filter by who took action
    #[prost(string, optional, tag="2")]
    pub moderator_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Filter by who was affected
    #[prost(string, optional, tag="3")]
    pub target_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ModerationActionType", optional, tag="4")]
    pub action_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="5")]
    pub limit: ::core::option::Option<i32>,
    #[prost(string, optional, tag="6")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetModerationLogResponse {
    #[prost(message, repeated, tag="1")]
    pub entries: ::prost::alloc::vec::Vec<ModerationLogEntry>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModerationLogEntry {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub moderator_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub moderator_name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub target_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub target_user_name: ::prost::alloc::string::String,
    #[prost(enumeration="ModerationActionType", tag="7")]
    pub action_type: i32,
    #[prost(string, optional, tag="8")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    /// Additional context (e.g., duration, message_pid)
    #[prost(map="string, string", tag="9")]
    pub metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag="10")]
    pub created_at: ::prost::alloc::string::String,
}
// ============================================================================
// Auto-moderation
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAutoModSettingsRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAutoModSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub settings: ::core::option::Option<AutoModSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAutoModSettingsRequest {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub settings: ::core::option::Option<AutoModSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAutoModSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub settings: ::core::option::Option<AutoModSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AutoModSettings {
    #[prost(bool, tag="1")]
    pub enabled: bool,
    /// Spam detection
    #[prost(bool, tag="2")]
    pub spam_filter_enabled: bool,
    #[prost(int32, tag="3")]
    pub max_messages_per_minute: i32,
    #[prost(int32, tag="4")]
    pub max_duplicate_messages: i32,
    /// Content filtering
    #[prost(bool, tag="5")]
    pub profanity_filter_enabled: bool,
    #[prost(enumeration="ProfanityFilterLevel", tag="6")]
    pub profanity_filter_level: i32,
    #[prost(string, repeated, tag="7")]
    pub custom_blocked_words: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="8")]
    pub custom_allowed_words: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Link filtering
    #[prost(bool, tag="9")]
    pub link_filter_enabled: bool,
    #[prost(string, repeated, tag="10")]
    pub allowed_domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag="11")]
    pub block_all_links: bool,
    /// Mention limits
    #[prost(int32, tag="12")]
    pub max_mentions_per_message: i32,
    #[prost(bool, tag="13")]
    pub block_everyone_mentions: bool,
    #[prost(bool, tag="14")]
    pub block_role_mentions: bool,
    /// Actions
    #[prost(enumeration="AutoModAction", tag="15")]
    pub default_action: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReportStatus {
    Unspecified = 0,
    Pending = 1,
    Reviewing = 2,
    Resolved = 3,
    Dismissed = 4,
}
impl ReportStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REPORT_STATUS_UNSPECIFIED",
            Self::Pending => "REPORT_STATUS_PENDING",
            Self::Reviewing => "REPORT_STATUS_REVIEWING",
            Self::Resolved => "REPORT_STATUS_RESOLVED",
            Self::Dismissed => "REPORT_STATUS_DISMISSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REPORT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "REPORT_STATUS_PENDING" => Some(Self::Pending),
            "REPORT_STATUS_REVIEWING" => Some(Self::Reviewing),
            "REPORT_STATUS_RESOLVED" => Some(Self::Resolved),
            "REPORT_STATUS_DISMISSED" => Some(Self::Dismissed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReportType {
    Unspecified = 0,
    Message = 1,
    User = 2,
}
impl ReportType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REPORT_TYPE_UNSPECIFIED",
            Self::Message => "REPORT_TYPE_MESSAGE",
            Self::User => "REPORT_TYPE_USER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REPORT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "REPORT_TYPE_MESSAGE" => Some(Self::Message),
            "REPORT_TYPE_USER" => Some(Self::User),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReportResolution {
    Unspecified = 0,
    NoAction = 1,
    WarningIssued = 2,
    ContentRemoved = 3,
    UserMuted = 4,
    UserBanned = 5,
}
impl ReportResolution {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REPORT_RESOLUTION_UNSPECIFIED",
            Self::NoAction => "REPORT_RESOLUTION_NO_ACTION",
            Self::WarningIssued => "REPORT_RESOLUTION_WARNING_ISSUED",
            Self::ContentRemoved => "REPORT_RESOLUTION_CONTENT_REMOVED",
            Self::UserMuted => "REPORT_RESOLUTION_USER_MUTED",
            Self::UserBanned => "REPORT_RESOLUTION_USER_BANNED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REPORT_RESOLUTION_UNSPECIFIED" => Some(Self::Unspecified),
            "REPORT_RESOLUTION_NO_ACTION" => Some(Self::NoAction),
            "REPORT_RESOLUTION_WARNING_ISSUED" => Some(Self::WarningIssued),
            "REPORT_RESOLUTION_CONTENT_REMOVED" => Some(Self::ContentRemoved),
            "REPORT_RESOLUTION_USER_MUTED" => Some(Self::UserMuted),
            "REPORT_RESOLUTION_USER_BANNED" => Some(Self::UserBanned),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ModerationActionType {
    Unspecified = 0,
    Mute = 1,
    Unmute = 2,
    Ban = 3,
    Unban = 4,
    Kick = 5,
    Warn = 6,
    DeleteMessage = 7,
    RoleChange = 8,
}
impl ModerationActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MODERATION_ACTION_TYPE_UNSPECIFIED",
            Self::Mute => "MODERATION_ACTION_TYPE_MUTE",
            Self::Unmute => "MODERATION_ACTION_TYPE_UNMUTE",
            Self::Ban => "MODERATION_ACTION_TYPE_BAN",
            Self::Unban => "MODERATION_ACTION_TYPE_UNBAN",
            Self::Kick => "MODERATION_ACTION_TYPE_KICK",
            Self::Warn => "MODERATION_ACTION_TYPE_WARN",
            Self::DeleteMessage => "MODERATION_ACTION_TYPE_DELETE_MESSAGE",
            Self::RoleChange => "MODERATION_ACTION_TYPE_ROLE_CHANGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MODERATION_ACTION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "MODERATION_ACTION_TYPE_MUTE" => Some(Self::Mute),
            "MODERATION_ACTION_TYPE_UNMUTE" => Some(Self::Unmute),
            "MODERATION_ACTION_TYPE_BAN" => Some(Self::Ban),
            "MODERATION_ACTION_TYPE_UNBAN" => Some(Self::Unban),
            "MODERATION_ACTION_TYPE_KICK" => Some(Self::Kick),
            "MODERATION_ACTION_TYPE_WARN" => Some(Self::Warn),
            "MODERATION_ACTION_TYPE_DELETE_MESSAGE" => Some(Self::DeleteMessage),
            "MODERATION_ACTION_TYPE_ROLE_CHANGE" => Some(Self::RoleChange),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProfanityFilterLevel {
    Unspecified = 0,
    /// Only severe profanity
    Low = 1,
    /// Common profanity
    Medium = 2,
    /// Aggressive filtering
    High = 3,
}
impl ProfanityFilterLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROFANITY_FILTER_LEVEL_UNSPECIFIED",
            Self::Low => "PROFANITY_FILTER_LEVEL_LOW",
            Self::Medium => "PROFANITY_FILTER_LEVEL_MEDIUM",
            Self::High => "PROFANITY_FILTER_LEVEL_HIGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROFANITY_FILTER_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "PROFANITY_FILTER_LEVEL_LOW" => Some(Self::Low),
            "PROFANITY_FILTER_LEVEL_MEDIUM" => Some(Self::Medium),
            "PROFANITY_FILTER_LEVEL_HIGH" => Some(Self::High),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AutoModAction {
    Unspecified = 0,
    /// Flag for review
    Flag = 1,
    /// Delete message
    Delete = 2,
    /// Mute user temporarily
    Mute = 3,
    /// Send warning to user
    Warn = 4,
}
impl AutoModAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUTO_MOD_ACTION_UNSPECIFIED",
            Self::Flag => "AUTO_MOD_ACTION_FLAG",
            Self::Delete => "AUTO_MOD_ACTION_DELETE",
            Self::Mute => "AUTO_MOD_ACTION_MUTE",
            Self::Warn => "AUTO_MOD_ACTION_WARN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTO_MOD_ACTION_UNSPECIFIED" => Some(Self::Unspecified),
            "AUTO_MOD_ACTION_FLAG" => Some(Self::Flag),
            "AUTO_MOD_ACTION_DELETE" => Some(Self::Delete),
            "AUTO_MOD_ACTION_MUTE" => Some(Self::Mute),
            "AUTO_MOD_ACTION_WARN" => Some(Self::Warn),
            _ => None,
        }
    }
}
include!("chat.v1.serde.rs");
include!("chat.v1.tonic.rs");
// @@protoc_insertion_point(module)