// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file api/v1/admin.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/admin.proto.
 */
export const file_api_v1_admin: GenFile = /*@__PURE__*/
  fileDesc("ChJhcGkvdjEvYWRtaW4ucHJvdG8SBmFwaS52MSKKAQoQT3JnYW5pemF0aW9uUGxhbhIYChBvcmdhbml6YXRpb25fcGlkGAEgASgJEgwKBHRpZXIYAiABKAkSFwoKZXhwaXJlc19hdBgDIAEoCUgAiAEBEhIKCmNyZWF0ZWRfYXQYBCABKAkSEgoKdXBkYXRlZF9hdBgFIAEoCUINCgtfZXhwaXJlc19hdCI2ChpHZXRPcmdhbml6YXRpb25QbGFuUmVxdWVzdBIYChBvcmdhbml6YXRpb25fcGlkGAEgASgJIkUKG0dldE9yZ2FuaXphdGlvblBsYW5SZXNwb25zZRImCgRwbGFuGAEgASgLMhguYXBpLnYxLk9yZ2FuaXphdGlvblBsYW4ifQodVXBkYXRlT3JnYW5pemF0aW9uUGxhblJlcXVlc3QSGAoQb3JnYW5pemF0aW9uX3BpZBgBIAEoCRIRCgR0aWVyGAIgASgJSACIAQESFwoKZXhwaXJlc19hdBgDIAEoCUgBiAEBQgcKBV90aWVyQg0KC19leHBpcmVzX2F0IkgKHlVwZGF0ZU9yZ2FuaXphdGlvblBsYW5SZXNwb25zZRImCgRwbGFuGAEgASgLMhguYXBpLnYxLk9yZ2FuaXphdGlvblBsYW4y1wEKDEFkbWluU2VydmljZRJeChNHZXRPcmdhbml6YXRpb25QbGFuEiIuYXBpLnYxLkdldE9yZ2FuaXphdGlvblBsYW5SZXF1ZXN0GiMuYXBpLnYxLkdldE9yZ2FuaXphdGlvblBsYW5SZXNwb25zZRJnChZVcGRhdGVPcmdhbml6YXRpb25QbGFuEiUuYXBpLnYxLlVwZGF0ZU9yZ2FuaXphdGlvblBsYW5SZXF1ZXN0GiYuYXBpLnYxLlVwZGF0ZU9yZ2FuaXphdGlvblBsYW5SZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message api.v1.OrganizationPlan
 */
export type OrganizationPlan = Message<"api.v1.OrganizationPlan"> & {
  /**
   * @generated from field: string organization_pid = 1;
   */
  organizationPid: string;

  /**
   * @generated from field: string tier = 2;
   */
  tier: string;

  /**
   * @generated from field: optional string expires_at = 3;
   */
  expiresAt?: string;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 5;
   */
  updatedAt: string;
};

/**
 * Describes the message api.v1.OrganizationPlan.
 * Use `create(OrganizationPlanSchema)` to create a new message.
 */
export const OrganizationPlanSchema: GenMessage<OrganizationPlan> = /*@__PURE__*/
  messageDesc(file_api_v1_admin, 0);

/**
 * @generated from message api.v1.GetOrganizationPlanRequest
 */
export type GetOrganizationPlanRequest = Message<"api.v1.GetOrganizationPlanRequest"> & {
  /**
   * @generated from field: string organization_pid = 1;
   */
  organizationPid: string;
};

/**
 * Describes the message api.v1.GetOrganizationPlanRequest.
 * Use `create(GetOrganizationPlanRequestSchema)` to create a new message.
 */
export const GetOrganizationPlanRequestSchema: GenMessage<GetOrganizationPlanRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_admin, 1);

/**
 * @generated from message api.v1.GetOrganizationPlanResponse
 */
export type GetOrganizationPlanResponse = Message<"api.v1.GetOrganizationPlanResponse"> & {
  /**
   * @generated from field: api.v1.OrganizationPlan plan = 1;
   */
  plan?: OrganizationPlan;
};

/**
 * Describes the message api.v1.GetOrganizationPlanResponse.
 * Use `create(GetOrganizationPlanResponseSchema)` to create a new message.
 */
export const GetOrganizationPlanResponseSchema: GenMessage<GetOrganizationPlanResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_admin, 2);

/**
 * @generated from message api.v1.UpdateOrganizationPlanRequest
 */
export type UpdateOrganizationPlanRequest = Message<"api.v1.UpdateOrganizationPlanRequest"> & {
  /**
   * @generated from field: string organization_pid = 1;
   */
  organizationPid: string;

  /**
   * @generated from field: optional string tier = 2;
   */
  tier?: string;

  /**
   * @generated from field: optional string expires_at = 3;
   */
  expiresAt?: string;
};

/**
 * Describes the message api.v1.UpdateOrganizationPlanRequest.
 * Use `create(UpdateOrganizationPlanRequestSchema)` to create a new message.
 */
export const UpdateOrganizationPlanRequestSchema: GenMessage<UpdateOrganizationPlanRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_admin, 3);

/**
 * @generated from message api.v1.UpdateOrganizationPlanResponse
 */
export type UpdateOrganizationPlanResponse = Message<"api.v1.UpdateOrganizationPlanResponse"> & {
  /**
   * @generated from field: api.v1.OrganizationPlan plan = 1;
   */
  plan?: OrganizationPlan;
};

/**
 * Describes the message api.v1.UpdateOrganizationPlanResponse.
 * Use `create(UpdateOrganizationPlanResponseSchema)` to create a new message.
 */
export const UpdateOrganizationPlanResponseSchema: GenMessage<UpdateOrganizationPlanResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_admin, 4);

/**
 * @generated from service api.v1.AdminService
 */
export const AdminService: GenService<{
  /**
   * @generated from rpc api.v1.AdminService.GetOrganizationPlan
   */
  getOrganizationPlan: {
    methodKind: "unary";
    input: typeof GetOrganizationPlanRequestSchema;
    output: typeof GetOrganizationPlanResponseSchema;
  },
  /**
   * @generated from rpc api.v1.AdminService.UpdateOrganizationPlan
   */
  updateOrganizationPlan: {
    methodKind: "unary";
    input: typeof UpdateOrganizationPlanRequestSchema;
    output: typeof UpdateOrganizationPlanResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_admin, 0);

