// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file api/v1/billing.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/billing.proto.
 */
export const file_api_v1_billing: GenFile = /*@__PURE__*/
  fileDesc("ChRhcGkvdjEvYmlsbGluZy5wcm90bxIGYXBpLnYxIhcKFUdldEN1cnJlbnRQbGFuUmVxdWVzdCJcChZHZXRDdXJyZW50UGxhblJlc3BvbnNlEhoKBHRpZXIYASABKA4yDC5hcGkudjEuVGllchIXCgpleHBpcmVzX2F0GAIgASgJSACIAQFCDQoLX2V4cGlyZXNfYXQiEwoRR2V0UHJpY2luZ1JlcXVlc3QiOAoSR2V0UHJpY2luZ1Jlc3BvbnNlEiIKBXRpZXJzGAEgAygLMhMuYXBpLnYxLlByaWNpbmdUaWVyIowBCgtQcmljaW5nVGllchIaCgR0aWVyGAEgASgOMgwuYXBpLnYxLlRpZXISDAoEbmFtZRgCIAEoCRITCgtwcmljZV9jZW50cxgDIAEoBRIaChJhbm51YWxfcHJpY2VfY2VudHMYBCABKAUSEAoIY3VycmVuY3kYBSABKAkSEAoIZmVhdHVyZXMYBiADKAkiZQocQ3JlYXRlQ2hlY2tvdXRTZXNzaW9uUmVxdWVzdBIaCgR0aWVyGAEgASgOMgwuYXBpLnYxLlRpZXISKQoIaW50ZXJ2YWwYAiABKA4yFy5hcGkudjEuQmlsbGluZ0ludGVydmFsImIKHUNyZWF0ZUNoZWNrb3V0U2Vzc2lvblJlc3BvbnNlEhQKDHJlZGlyZWN0X3VybBgBIAEoCRIrCg1yZWRpcmVjdF90eXBlGAIgASgOMhQuYXBpLnYxLlJlZGlyZWN0VHlwZSIcChpDcmVhdGVQb3J0YWxTZXNzaW9uUmVxdWVzdCIxChtDcmVhdGVQb3J0YWxTZXNzaW9uUmVzcG9uc2USEgoKcG9ydGFsX3VybBgBIAEoCSpdCgRUaWVyEhQKEFRJRVJfVU5TUEVDSUZJRUQQABINCglUSUVSX0ZSRUUQARINCglUSUVSX1BMVVMQAhIMCghUSUVSX1BSTxADEhMKD1RJRVJfRU5URVJQUklTRRAEKmMKDFJlZGlyZWN0VHlwZRIdChlSRURJUkVDVF9UWVBFX1VOU1BFQ0lGSUVEEAASGgoWUkVESVJFQ1RfVFlQRV9DSEVDS09VVBABEhgKFFJFRElSRUNUX1RZUEVfUE9SVEFMEAIqbgoPQmlsbGluZ0ludGVydmFsEiAKHEJJTExJTkdfSU5URVJWQUxfVU5TUEVDSUZJRUQQABIcChhCSUxMSU5HX0lOVEVSVkFMX01PTlRITFkQARIbChdCSUxMSU5HX0lOVEVSVkFMX0FOTlVBTBACMuwCCg5CaWxsaW5nU2VydmljZRJPCg5HZXRDdXJyZW50UGxhbhIdLmFwaS52MS5HZXRDdXJyZW50UGxhblJlcXVlc3QaHi5hcGkudjEuR2V0Q3VycmVudFBsYW5SZXNwb25zZRJDCgpHZXRQcmljaW5nEhkuYXBpLnYxLkdldFByaWNpbmdSZXF1ZXN0GhouYXBpLnYxLkdldFByaWNpbmdSZXNwb25zZRJkChVDcmVhdGVDaGVja291dFNlc3Npb24SJC5hcGkudjEuQ3JlYXRlQ2hlY2tvdXRTZXNzaW9uUmVxdWVzdBolLmFwaS52MS5DcmVhdGVDaGVja291dFNlc3Npb25SZXNwb25zZRJeChNDcmVhdGVQb3J0YWxTZXNzaW9uEiIuYXBpLnYxLkNyZWF0ZVBvcnRhbFNlc3Npb25SZXF1ZXN0GiMuYXBpLnYxLkNyZWF0ZVBvcnRhbFNlc3Npb25SZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message api.v1.GetCurrentPlanRequest
 */
export type GetCurrentPlanRequest = Message<"api.v1.GetCurrentPlanRequest"> & {
};

/**
 * Describes the message api.v1.GetCurrentPlanRequest.
 * Use `create(GetCurrentPlanRequestSchema)` to create a new message.
 */
export const GetCurrentPlanRequestSchema: GenMessage<GetCurrentPlanRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 0);

/**
 * @generated from message api.v1.GetCurrentPlanResponse
 */
export type GetCurrentPlanResponse = Message<"api.v1.GetCurrentPlanResponse"> & {
  /**
   * @generated from field: api.v1.Tier tier = 1;
   */
  tier: Tier;

  /**
   * @generated from field: optional string expires_at = 2;
   */
  expiresAt?: string;
};

/**
 * Describes the message api.v1.GetCurrentPlanResponse.
 * Use `create(GetCurrentPlanResponseSchema)` to create a new message.
 */
export const GetCurrentPlanResponseSchema: GenMessage<GetCurrentPlanResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 1);

/**
 * @generated from message api.v1.GetPricingRequest
 */
export type GetPricingRequest = Message<"api.v1.GetPricingRequest"> & {
};

/**
 * Describes the message api.v1.GetPricingRequest.
 * Use `create(GetPricingRequestSchema)` to create a new message.
 */
export const GetPricingRequestSchema: GenMessage<GetPricingRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 2);

/**
 * @generated from message api.v1.GetPricingResponse
 */
export type GetPricingResponse = Message<"api.v1.GetPricingResponse"> & {
  /**
   * @generated from field: repeated api.v1.PricingTier tiers = 1;
   */
  tiers: PricingTier[];
};

/**
 * Describes the message api.v1.GetPricingResponse.
 * Use `create(GetPricingResponseSchema)` to create a new message.
 */
export const GetPricingResponseSchema: GenMessage<GetPricingResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 3);

/**
 * @generated from message api.v1.PricingTier
 */
export type PricingTier = Message<"api.v1.PricingTier"> & {
  /**
   * @generated from field: api.v1.Tier tier = 1;
   */
  tier: Tier;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 price_cents = 3;
   */
  priceCents: number;

  /**
   * @generated from field: int32 annual_price_cents = 4;
   */
  annualPriceCents: number;

  /**
   * @generated from field: string currency = 5;
   */
  currency: string;

  /**
   * @generated from field: repeated string features = 6;
   */
  features: string[];
};

/**
 * Describes the message api.v1.PricingTier.
 * Use `create(PricingTierSchema)` to create a new message.
 */
export const PricingTierSchema: GenMessage<PricingTier> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 4);

/**
 * @generated from message api.v1.CreateCheckoutSessionRequest
 */
export type CreateCheckoutSessionRequest = Message<"api.v1.CreateCheckoutSessionRequest"> & {
  /**
   * @generated from field: api.v1.Tier tier = 1;
   */
  tier: Tier;

  /**
   * @generated from field: api.v1.BillingInterval interval = 2;
   */
  interval: BillingInterval;
};

/**
 * Describes the message api.v1.CreateCheckoutSessionRequest.
 * Use `create(CreateCheckoutSessionRequestSchema)` to create a new message.
 */
export const CreateCheckoutSessionRequestSchema: GenMessage<CreateCheckoutSessionRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 5);

/**
 * @generated from message api.v1.CreateCheckoutSessionResponse
 */
export type CreateCheckoutSessionResponse = Message<"api.v1.CreateCheckoutSessionResponse"> & {
  /**
   * URL to redirect user to (checkout or portal)
   *
   * @generated from field: string redirect_url = 1;
   */
  redirectUrl: string;

  /**
   * Indicates where user is being sent
   *
   * @generated from field: api.v1.RedirectType redirect_type = 2;
   */
  redirectType: RedirectType;
};

/**
 * Describes the message api.v1.CreateCheckoutSessionResponse.
 * Use `create(CreateCheckoutSessionResponseSchema)` to create a new message.
 */
export const CreateCheckoutSessionResponseSchema: GenMessage<CreateCheckoutSessionResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 6);

/**
 * @generated from message api.v1.CreatePortalSessionRequest
 */
export type CreatePortalSessionRequest = Message<"api.v1.CreatePortalSessionRequest"> & {
};

/**
 * Describes the message api.v1.CreatePortalSessionRequest.
 * Use `create(CreatePortalSessionRequestSchema)` to create a new message.
 */
export const CreatePortalSessionRequestSchema: GenMessage<CreatePortalSessionRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 7);

/**
 * @generated from message api.v1.CreatePortalSessionResponse
 */
export type CreatePortalSessionResponse = Message<"api.v1.CreatePortalSessionResponse"> & {
  /**
   * @generated from field: string portal_url = 1;
   */
  portalUrl: string;
};

/**
 * Describes the message api.v1.CreatePortalSessionResponse.
 * Use `create(CreatePortalSessionResponseSchema)` to create a new message.
 */
export const CreatePortalSessionResponseSchema: GenMessage<CreatePortalSessionResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_billing, 8);

/**
 * @generated from enum api.v1.Tier
 */
export enum Tier {
  /**
   * @generated from enum value: TIER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TIER_FREE = 1;
   */
  FREE = 1,

  /**
   * @generated from enum value: TIER_PLUS = 2;
   */
  PLUS = 2,

  /**
   * @generated from enum value: TIER_PRO = 3;
   */
  PRO = 3,

  /**
   * @generated from enum value: TIER_ENTERPRISE = 4;
   */
  ENTERPRISE = 4,
}

/**
 * Describes the enum api.v1.Tier.
 */
export const TierSchema: GenEnum<Tier> = /*@__PURE__*/
  enumDesc(file_api_v1_billing, 0);

/**
 * @generated from enum api.v1.RedirectType
 */
export enum RedirectType {
  /**
   * @generated from enum value: REDIRECT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * New subscription checkout
   *
   * @generated from enum value: REDIRECT_TYPE_CHECKOUT = 1;
   */
  CHECKOUT = 1,

  /**
   * Existing customer portal (manage/upgrade/resubscribe)
   *
   * @generated from enum value: REDIRECT_TYPE_PORTAL = 2;
   */
  PORTAL = 2,
}

/**
 * Describes the enum api.v1.RedirectType.
 */
export const RedirectTypeSchema: GenEnum<RedirectType> = /*@__PURE__*/
  enumDesc(file_api_v1_billing, 1);

/**
 * @generated from enum api.v1.BillingInterval
 */
export enum BillingInterval {
  /**
   * @generated from enum value: BILLING_INTERVAL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BILLING_INTERVAL_MONTHLY = 1;
   */
  MONTHLY = 1,

  /**
   * @generated from enum value: BILLING_INTERVAL_ANNUAL = 2;
   */
  ANNUAL = 2,
}

/**
 * Describes the enum api.v1.BillingInterval.
 */
export const BillingIntervalSchema: GenEnum<BillingInterval> = /*@__PURE__*/
  enumDesc(file_api_v1_billing, 2);

/**
 * @generated from service api.v1.BillingService
 */
export const BillingService: GenService<{
  /**
   * @generated from rpc api.v1.BillingService.GetCurrentPlan
   */
  getCurrentPlan: {
    methodKind: "unary";
    input: typeof GetCurrentPlanRequestSchema;
    output: typeof GetCurrentPlanResponseSchema;
  },
  /**
   * @generated from rpc api.v1.BillingService.GetPricing
   */
  getPricing: {
    methodKind: "unary";
    input: typeof GetPricingRequestSchema;
    output: typeof GetPricingResponseSchema;
  },
  /**
   * @generated from rpc api.v1.BillingService.CreateCheckoutSession
   */
  createCheckoutSession: {
    methodKind: "unary";
    input: typeof CreateCheckoutSessionRequestSchema;
    output: typeof CreateCheckoutSessionResponseSchema;
  },
  /**
   * @generated from rpc api.v1.BillingService.CreatePortalSession
   */
  createPortalSession: {
    methodKind: "unary";
    input: typeof CreatePortalSessionRequestSchema;
    output: typeof CreatePortalSessionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_billing, 0);

