//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "organization_role_enum")]
pub enum OrganizationRoleEnum {
    #[sea_orm(string_value = "Owner")]
    Owner,
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Member")]
    Member,
    #[sea_orm(string_value = "Guest")]
    Guest,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "plan_tier_enum")]
pub enum PlanTierEnum {
    #[sea_orm(string_value = "Free")]
    Free,
    #[sea_orm(string_value = "Pro")]
    Pro,
    #[sea_orm(string_value = "Plus")]
    Plus,
    #[sea_orm(string_value = "Enterprise")]
    Enterprise,
}
