//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ChannelType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "channels")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: String,
    pub name: String,
    pub channel_type: ChannelType,
    pub description: Option<String>,
    pub organization_pid: Option<String>,
    pub icon_url: Option<String>,
    pub archived: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::auto_mod_settings::Entity")]
    AutoModSettings,
    #[sea_orm(has_many = "super::channel_bans::Entity")]
    ChannelBans,
    #[sea_orm(has_many = "super::channel_events::Entity")]
    ChannelEvents,
    #[sea_orm(has_many = "super::channel_members::Entity")]
    ChannelMembers,
    #[sea_orm(has_many = "super::channel_mutes::Entity")]
    ChannelMutes,
    #[sea_orm(has_many = "super::message_reports::Entity")]
    MessageReports,
    #[sea_orm(has_many = "super::moderation_log::Entity")]
    ModerationLog,
    #[sea_orm(has_many = "super::read_receipts::Entity")]
    ReadReceipts,
}

impl Related<super::auto_mod_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutoModSettings.def()
    }
}

impl Related<super::channel_bans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelBans.def()
    }
}

impl Related<super::channel_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelEvents.def()
    }
}

impl Related<super::channel_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelMembers.def()
    }
}

impl Related<super::channel_mutes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelMutes.def()
    }
}

impl Related<super::message_reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageReports.def()
    }
}

impl Related<super::moderation_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModerationLog.def()
    }
}

impl Related<super::read_receipts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReadReceipts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
