//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::MessageKind;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "channel_events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: String,
    pub channel_id: String,
    pub message_kind: MessageKind,
    pub user_id: Option<String>,
    pub sender_name: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub content: Json,
    pub parent_pid: Option<String>,
    pub timestamp: DateTimeWithTimeZone,
    pub is_deleted: bool,
    pub is_edited: bool,
    pub edited_at: Option<DateTimeWithTimeZone>,
    pub is_pinned: bool,
    pub pinned_at: Option<DateTimeWithTimeZone>,
    pub pinned_by_user_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::Pid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channels,
    #[sea_orm(has_many = "super::message_attachments::Entity")]
    MessageAttachments,
    #[sea_orm(has_many = "super::message_reactions::Entity")]
    MessageReactions,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::message_attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageAttachments.def()
    }
}

impl Related<super::message_reactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageReactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
