//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "message_reactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub message_pid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub emoji: String,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_events::Entity",
        from = "Column::MessagePid",
        to = "super::channel_events::Column::Pid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ChannelEvents,
}

impl Related<super::channel_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
