//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ReportReason;
use super::sea_orm_active_enums::ReportResolution;
use super::sea_orm_active_enums::ReportStatus;
use super::sea_orm_active_enums::ReportType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "message_reports")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: String,
    pub report_type: ReportType,
    #[sea_orm(unique_key = "idx_message_reports_unique_user_message")]
    pub reporter_id: String,
    #[sea_orm(unique_key = "idx_message_reports_unique_user_message")]
    pub target_message_pid: Option<String>,
    pub target_user_id: Option<String>,
    pub channel_id: String,
    pub reason: ReportReason,
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    pub status: ReportStatus,
    pub resolution: Option<ReportResolution>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub resolved_by_user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub resolution_notes: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::Pid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channels,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
