//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auto_mod_action")]
pub enum AutoModAction {
    #[sea_orm(string_value = "flag")]
    Flag,
    #[sea_orm(string_value = "delete")]
    Delete,
    #[sea_orm(string_value = "mute")]
    Mute,
    #[sea_orm(string_value = "warn")]
    Warn,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_role")]
pub enum ChannelRole {
    #[sea_orm(string_value = "member")]
    Member,
    #[sea_orm(string_value = "moderator")]
    Moderator,
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "owner")]
    Owner,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_type")]
pub enum ChannelType {
    #[sea_orm(string_value = "global")]
    Global,
    #[sea_orm(string_value = "organization")]
    Organization,
    #[sea_orm(string_value = "private")]
    Private,
    #[sea_orm(string_value = "system")]
    System,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "message_kind")]
pub enum MessageKind {
    #[sea_orm(string_value = "user")]
    User,
    #[sea_orm(string_value = "agent")]
    Agent,
    #[sea_orm(string_value = "system")]
    System,
    #[sea_orm(string_value = "unknown")]
    Unknown,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "moderation_action_type")]
pub enum ModerationActionType {
    #[sea_orm(string_value = "mute")]
    Mute,
    #[sea_orm(string_value = "unmute")]
    Unmute,
    #[sea_orm(string_value = "ban")]
    Ban,
    #[sea_orm(string_value = "unban")]
    Unban,
    #[sea_orm(string_value = "kick")]
    Kick,
    #[sea_orm(string_value = "warn")]
    Warn,
    #[sea_orm(string_value = "delete_message")]
    DeleteMessage,
    #[sea_orm(string_value = "role_change")]
    RoleChange,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "profanity_filter_level")]
pub enum ProfanityFilterLevel {
    #[sea_orm(string_value = "low")]
    Low,
    #[sea_orm(string_value = "medium")]
    Medium,
    #[sea_orm(string_value = "high")]
    High,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_reason")]
pub enum ReportReason {
    #[sea_orm(string_value = "spam")]
    Spam,
    #[sea_orm(string_value = "harassment")]
    Harassment,
    #[sea_orm(string_value = "hate_speech")]
    HateSpeech,
    #[sea_orm(string_value = "violence")]
    Violence,
    #[sea_orm(string_value = "nsfw")]
    Nsfw,
    #[sea_orm(string_value = "misinformation")]
    Misinformation,
    #[sea_orm(string_value = "other")]
    Other,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_resolution")]
pub enum ReportResolution {
    #[sea_orm(string_value = "no_action")]
    NoAction,
    #[sea_orm(string_value = "warning_issued")]
    WarningIssued,
    #[sea_orm(string_value = "content_removed")]
    ContentRemoved,
    #[sea_orm(string_value = "user_muted")]
    UserMuted,
    #[sea_orm(string_value = "user_banned")]
    UserBanned,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_status")]
pub enum ReportStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "reviewing")]
    Reviewing,
    #[sea_orm(string_value = "resolved")]
    Resolved,
    #[sea_orm(string_value = "dismissed")]
    Dismissed,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "report_type")]
pub enum ReportType {
    #[sea_orm(string_value = "message")]
    Message,
    #[sea_orm(string_value = "user")]
    User,
}
