// @generated
// This file is @generated by prost-build.
// ============================================================================
// Core types
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Item {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ItemStatus", tag="4")]
    pub status: i32,
    #[prost(int64, tag="5")]
    pub created_at: i64,
    #[prost(int64, tag="6")]
    pub updated_at: i64,
}
// ============================================================================
// Requests & Responses
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetItemRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetItemResponse {
    #[prost(message, optional, tag="1")]
    pub item: ::core::option::Option<Item>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateItemRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub idempotency_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateItemResponse {
    #[prost(message, optional, tag="1")]
    pub item: ::core::option::Option<Item>,
    #[prost(bool, tag="2")]
    pub deduplicated: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListItemsRequest {
    #[prost(int32, tag="1")]
    pub limit: i32,
    #[prost(string, optional, tag="2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ItemStatus", optional, tag="3")]
    pub status: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListItemsResponse {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<Item>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub total_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateItemRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ItemStatus", optional, tag="4")]
    pub status: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateItemResponse {
    #[prost(message, optional, tag="1")]
    pub item: ::core::option::Option<Item>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteItemRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
// ============================================================================
// Streaming
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchItemsRequest {
    #[prost(enumeration="ItemStatus", optional, tag="1")]
    pub status: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemEvent {
    #[prost(oneof="item_event::Event", tags="1, 2, 3")]
    pub event: ::core::option::Option<item_event::Event>,
}
/// Nested message and enum types in `ItemEvent`.
pub mod item_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="1")]
        Created(super::Item),
        #[prost(message, tag="2")]
        Updated(super::Item),
        #[prost(message, tag="3")]
        Deleted(super::ItemDeleted),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ItemDeleted {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ItemStatus {
    Unspecified = 0,
    Draft = 1,
    Active = 2,
    Archived = 3,
}
impl ItemStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ITEM_STATUS_UNSPECIFIED",
            Self::Draft => "ITEM_STATUS_DRAFT",
            Self::Active => "ITEM_STATUS_ACTIVE",
            Self::Archived => "ITEM_STATUS_ARCHIVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ITEM_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "ITEM_STATUS_DRAFT" => Some(Self::Draft),
            "ITEM_STATUS_ACTIVE" => Some(Self::Active),
            "ITEM_STATUS_ARCHIVED" => Some(Self::Archived),
            _ => None,
        }
    }
}
include!("example.v1.serde.rs");
include!("example.v1.tonic.rs");
// @@protoc_insertion_point(module)