//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "organization_members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: String,
    #[sea_orm(unique_key = "idx_org_members_unique")]
    pub organization_id: i32,
    #[sea_orm(unique_key = "idx_org_members_unique")]
    pub user_id: String,
    pub role: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Json,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "organization_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub organizations: HasOne<super::organizations::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}
