//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "organization_plans")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub organization_id: i32,
    pub tier: String,
    pub expires_at: Option<DateTime>,
    pub stripe_customer_id: Option<String>,
    pub stripe_subscription_id: Option<String>,
    pub billing_cycle_start: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "organization_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub organizations: HasOne<super::organizations::Entity>,
}
