// @generated
// This file is @generated by prost-build.
// ============================================================================
// Core types
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Notification {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub org_pid: ::prost::alloc::string::String,
    /// Content
    #[prost(string, tag="4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, optional, tag="6")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Classification
    #[prost(enumeration="NotificationCategory", tag="7")]
    pub category: i32,
    #[prost(enumeration="NotificationPriority", tag="8")]
    pub priority: i32,
    /// Actions (what happens when user clicks - can have multiple, e.g., "Retry" + "View")
    #[prost(message, repeated, tag="9")]
    pub actions: ::prost::alloc::vec::Vec<NotificationAction>,
    /// Origin (which service created this)
    #[prost(enumeration="OriginService", tag="10")]
    pub origin_service: i32,
    #[prost(enumeration="OriginEntityType", optional, tag="11")]
    pub origin_entity_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag="12")]
    pub origin_entity_pid: ::core::option::Option<::prost::alloc::string::String>,
    /// State
    #[prost(bool, tag="13")]
    pub is_read: bool,
    #[prost(string, optional, tag="14")]
    pub read_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="15")]
    pub is_dismissed: bool,
    /// Auto-dismiss after this time
    #[prost(string, optional, tag="16")]
    pub expires_at: ::core::option::Option<::prost::alloc::string::String>,
    /// Timestamps
    #[prost(string, tag="17")]
    pub created_at: ::prost::alloc::string::String,
    /// Updated on every modification (for ordering)
    #[prost(string, tag="18")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationAction {
    #[prost(enumeration="ActionType", tag="1")]
    pub kind: i32,
    /// Route path, URL, or endpoint
    #[prost(string, tag="2")]
    pub target: ::prost::alloc::string::String,
    /// Query params or body fields
    #[prost(map="string, string", tag="3")]
    pub params: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ============================================================================
// Notification templates (common patterns)
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatMentionContext {
    #[prost(string, tag="1")]
    pub channel_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub channel_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub sender_name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub message_preview: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentCompleteContext {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub agent_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub run_pid: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub success: bool,
    #[prost(string, optional, tag="5")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub result_summary: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemAlertContext {
    /// "maintenance", "quota", "security"
    #[prost(string, tag="1")]
    pub alert_type: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="2")]
    pub details: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
// ============================================================================
// Enums
// ============================================================================

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NotificationPriority {
    Unspecified = 0,
    Low = 1,
    Normal = 2,
    High = 3,
    Urgent = 4,
}
impl NotificationPriority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NOTIFICATION_PRIORITY_UNSPECIFIED",
            Self::Low => "NOTIFICATION_PRIORITY_LOW",
            Self::Normal => "NOTIFICATION_PRIORITY_NORMAL",
            Self::High => "NOTIFICATION_PRIORITY_HIGH",
            Self::Urgent => "NOTIFICATION_PRIORITY_URGENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOTIFICATION_PRIORITY_UNSPECIFIED" => Some(Self::Unspecified),
            "NOTIFICATION_PRIORITY_LOW" => Some(Self::Low),
            "NOTIFICATION_PRIORITY_NORMAL" => Some(Self::Normal),
            "NOTIFICATION_PRIORITY_HIGH" => Some(Self::High),
            "NOTIFICATION_PRIORITY_URGENT" => Some(Self::Urgent),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NotificationCategory {
    Unspecified = 0,
    /// Chat mentions, messages
    Chat = 1,
    /// Agent run complete, errors
    Agent = 2,
    /// Plan changes, maintenance
    System = 3,
    /// Content warnings, bans
    Moderation = 4,
    /// Payment, quota alerts
    Billing = 5,
    /// Follows, friend requests
    Social = 6,
}
impl NotificationCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NOTIFICATION_CATEGORY_UNSPECIFIED",
            Self::Chat => "NOTIFICATION_CATEGORY_CHAT",
            Self::Agent => "NOTIFICATION_CATEGORY_AGENT",
            Self::System => "NOTIFICATION_CATEGORY_SYSTEM",
            Self::Moderation => "NOTIFICATION_CATEGORY_MODERATION",
            Self::Billing => "NOTIFICATION_CATEGORY_BILLING",
            Self::Social => "NOTIFICATION_CATEGORY_SOCIAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NOTIFICATION_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "NOTIFICATION_CATEGORY_CHAT" => Some(Self::Chat),
            "NOTIFICATION_CATEGORY_AGENT" => Some(Self::Agent),
            "NOTIFICATION_CATEGORY_SYSTEM" => Some(Self::System),
            "NOTIFICATION_CATEGORY_MODERATION" => Some(Self::Moderation),
            "NOTIFICATION_CATEGORY_BILLING" => Some(Self::Billing),
            "NOTIFICATION_CATEGORY_SOCIAL" => Some(Self::Social),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActionType {
    Unspecified = 0,
    /// Navigate to a page/route
    Navigate = 1,
    /// Trigger a POST request (e.g., accept invite)
    Post = 2,
    /// Fetch and display data
    Get = 3,
    /// Just dismiss, no action
    Dismiss = 4,
    /// Open external URL
    External = 5,
    /// Open a modal/dialog
    Modal = 6,
    /// Trigger file download
    Download = 7,
}
impl ActionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ACTION_TYPE_UNSPECIFIED",
            Self::Navigate => "ACTION_TYPE_NAVIGATE",
            Self::Post => "ACTION_TYPE_POST",
            Self::Get => "ACTION_TYPE_GET",
            Self::Dismiss => "ACTION_TYPE_DISMISS",
            Self::External => "ACTION_TYPE_EXTERNAL",
            Self::Modal => "ACTION_TYPE_MODAL",
            Self::Download => "ACTION_TYPE_DOWNLOAD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTION_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ACTION_TYPE_NAVIGATE" => Some(Self::Navigate),
            "ACTION_TYPE_POST" => Some(Self::Post),
            "ACTION_TYPE_GET" => Some(Self::Get),
            "ACTION_TYPE_DISMISS" => Some(Self::Dismiss),
            "ACTION_TYPE_EXTERNAL" => Some(Self::External),
            "ACTION_TYPE_MODAL" => Some(Self::Modal),
            "ACTION_TYPE_DOWNLOAD" => Some(Self::Download),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OriginService {
    Unspecified = 0,
    /// api-service
    Api = 1,
    /// chat-service
    Chat = 2,
    /// rig-service
    Rig = 3,
    /// agent-service
    Agent = 4,
    /// notification-service (system notifications)
    Notification = 5,
}
impl OriginService {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORIGIN_SERVICE_UNSPECIFIED",
            Self::Api => "ORIGIN_SERVICE_API",
            Self::Chat => "ORIGIN_SERVICE_CHAT",
            Self::Rig => "ORIGIN_SERVICE_RIG",
            Self::Agent => "ORIGIN_SERVICE_AGENT",
            Self::Notification => "ORIGIN_SERVICE_NOTIFICATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORIGIN_SERVICE_UNSPECIFIED" => Some(Self::Unspecified),
            "ORIGIN_SERVICE_API" => Some(Self::Api),
            "ORIGIN_SERVICE_CHAT" => Some(Self::Chat),
            "ORIGIN_SERVICE_RIG" => Some(Self::Rig),
            "ORIGIN_SERVICE_AGENT" => Some(Self::Agent),
            "ORIGIN_SERVICE_NOTIFICATION" => Some(Self::Notification),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OriginEntityType {
    Unspecified = 0,
    /// Chat channel
    Channel = 1,
    /// Chat message
    Message = 2,
    /// Agent definition
    Agent = 3,
    /// Agent run
    Run = 4,
    /// Workflow
    Workflow = 5,
    /// User action
    User = 6,
}
impl OriginEntityType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ORIGIN_ENTITY_TYPE_UNSPECIFIED",
            Self::Channel => "ORIGIN_ENTITY_TYPE_CHANNEL",
            Self::Message => "ORIGIN_ENTITY_TYPE_MESSAGE",
            Self::Agent => "ORIGIN_ENTITY_TYPE_AGENT",
            Self::Run => "ORIGIN_ENTITY_TYPE_RUN",
            Self::Workflow => "ORIGIN_ENTITY_TYPE_WORKFLOW",
            Self::User => "ORIGIN_ENTITY_TYPE_USER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORIGIN_ENTITY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ORIGIN_ENTITY_TYPE_CHANNEL" => Some(Self::Channel),
            "ORIGIN_ENTITY_TYPE_MESSAGE" => Some(Self::Message),
            "ORIGIN_ENTITY_TYPE_AGENT" => Some(Self::Agent),
            "ORIGIN_ENTITY_TYPE_RUN" => Some(Self::Run),
            "ORIGIN_ENTITY_TYPE_WORKFLOW" => Some(Self::Workflow),
            "ORIGIN_ENTITY_TYPE_USER" => Some(Self::User),
            _ => None,
        }
    }
}
// ============================================================================
// Push (service-to-service)
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_pid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="NotificationCategory", tag="6")]
    pub category: i32,
    #[prost(enumeration="NotificationPriority", tag="7")]
    pub priority: i32,
    #[prost(message, repeated, tag="8")]
    pub actions: ::prost::alloc::vec::Vec<NotificationAction>,
    /// Origin - typed enums, no guessing
    #[prost(enumeration="OriginService", tag="9")]
    pub origin_service: i32,
    #[prost(enumeration="OriginEntityType", optional, tag="10")]
    pub origin_entity_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag="11")]
    pub origin_entity_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub expires_at: ::core::option::Option<::prost::alloc::string::String>,
    /// Deduplication (e.g., don't spam same mention)
    #[prost(string, optional, tag="13")]
    pub idempotency_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushResponse {
    /// Internal ID for service-to-service updates
    #[prost(int64, tag="1")]
    pub id: i64,
    /// Public PID for client-facing use
    #[prost(string, tag="2")]
    pub notification_pid: ::prost::alloc::string::String,
    /// True if idempotency_key matched existing
    #[prost(bool, tag="3")]
    pub deduplicated: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushBatchRequest {
    #[prost(message, repeated, tag="1")]
    pub notifications: ::prost::alloc::vec::Vec<PushRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushBatchResponse {
    #[prost(uint64, tag="1")]
    pub created_count: u64,
    #[prost(uint64, tag="2")]
    pub deduplicated_count: u64,
    #[prost(string, repeated, tag="3")]
    pub notification_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// ============================================================================
// Update (service-to-service)
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateRequest {
    /// Internal ID from PushResponse
    #[prost(int64, tag="1")]
    pub id: i64,
    #[prost(string, optional, tag="2")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="NotificationPriority", optional, tag="5")]
    pub priority: ::core::option::Option<i32>,
    /// Empty = no change, non-empty = replace
    #[prost(message, repeated, tag="6")]
    pub actions: ::prost::alloc::vec::Vec<NotificationAction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateResponse {
    #[prost(message, optional, tag="1")]
    pub notification: ::core::option::Option<Notification>,
}
// ============================================================================
// PushStream (client streaming for live progress)
// ============================================================================

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PushStreamMessage {
    #[prost(oneof="push_stream_message::Message", tags="1, 2, 3")]
    pub message: ::core::option::Option<push_stream_message::Message>,
}
/// Nested message and enum types in `PushStreamMessage`.
pub mod push_stream_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        /// First message: creates the notification (persisted)
        #[prost(message, tag="1")]
        Init(super::PushRequest),
        /// Subsequent: live updates (ephemeral, not persisted)
        #[prost(message, tag="2")]
        Update(super::StreamUpdate),
        /// Optional final state before close (persisted)
        #[prost(message, tag="3")]
        Complete(super::StreamComplete),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamUpdate {
    #[prost(string, optional, tag="1")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="NotificationPriority", optional, tag="4")]
    pub priority: ::core::option::Option<i32>,
    /// Empty = no change, non-empty = replace
    #[prost(message, repeated, tag="5")]
    pub actions: ::prost::alloc::vec::Vec<NotificationAction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamComplete {
    #[prost(string, tag="1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub description: ::prost::alloc::string::String,
    /// Final actions (e.g., "View results", "Run again")
    #[prost(message, repeated, tag="3")]
    pub actions: ::prost::alloc::vec::Vec<NotificationAction>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushStreamResponse {
    #[prost(int64, tag="1")]
    pub id: i64,
    #[prost(string, tag="2")]
    pub notification_pid: ::prost::alloc::string::String,
}
// ============================================================================
// Real-time subscription
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeRequest {
    /// Optional filters for subscription
    #[prost(enumeration="NotificationCategory", repeated, tag="1")]
    pub categories: ::prost::alloc::vec::Vec<i32>,
    #[prost(enumeration="NotificationPriority", optional, tag="2")]
    pub min_priority: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationEvent {
    #[prost(oneof="notification_event::Event", tags="1, 2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<notification_event::Event>,
}
/// Nested message and enum types in `NotificationEvent`.
pub mod notification_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="1")]
        Notification(super::Notification),
        #[prost(message, tag="2")]
        Updated(super::NotificationUpdated),
        #[prost(message, tag="3")]
        Read(super::NotificationRead),
        #[prost(message, tag="4")]
        Dismissed(super::NotificationDismissed),
        #[prost(message, tag="5")]
        CountChanged(super::UnreadCountChanged),
        /// Ephemeral partial update from PushStream
        #[prost(message, tag="6")]
        Progress(super::NotificationProgress),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationUpdated {
    #[prost(message, optional, tag="1")]
    pub notification: ::core::option::Option<Notification>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotificationRead {
    #[prost(string, tag="1")]
    pub notification_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub read_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotificationDismissed {
    #[prost(string, tag="1")]
    pub notification_pid: ::prost::alloc::string::String,
}
/// Ephemeral progress update from PushStream.
/// All fields optional - only changed fields are present.
/// Client MUST merge with cached notification state.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotificationProgress {
    #[prost(string, tag="1")]
    pub notification_pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="NotificationPriority", optional, tag="5")]
    pub priority: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnreadCountChanged {
    #[prost(uint64, tag="1")]
    pub total_unread: u64,
    /// category name -> count
    #[prost(map="string, uint64", tag="2")]
    pub by_category: ::std::collections::HashMap<::prost::alloc::string::String, u64>,
}
// ============================================================================
// Query
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRequest {
    #[prost(bool, optional, tag="1")]
    pub unread_only: ::core::option::Option<bool>,
    #[prost(enumeration="NotificationCategory", repeated, tag="2")]
    pub categories: ::prost::alloc::vec::Vec<i32>,
    #[prost(enumeration="NotificationPriority", optional, tag="3")]
    pub min_priority: ::core::option::Option<i32>,
    #[prost(uint64, tag="4")]
    pub limit: u64,
    #[prost(string, optional, tag="5")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListResponse {
    #[prost(message, repeated, tag="1")]
    pub notifications: ::prost::alloc::vec::Vec<Notification>,
    #[prost(uint64, tag="2")]
    pub total_count: u64,
    #[prost(uint64, tag="3")]
    pub unread_count: u64,
    #[prost(string, optional, tag="4")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetRequest {
    #[prost(string, tag="1")]
    pub notification_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetResponse {
    #[prost(message, optional, tag="1")]
    pub notification: ::core::option::Option<Notification>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUnreadCountRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUnreadCountResponse {
    #[prost(uint64, tag="1")]
    pub total: u64,
    #[prost(map="string, uint64", tag="2")]
    pub by_category: ::std::collections::HashMap<::prost::alloc::string::String, u64>,
}
// ============================================================================
// State changes
// ============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAsReadRequest {
    #[prost(string, repeated, tag="1")]
    pub notification_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAllAsReadRequest {
    /// If set, only mark this category
    #[prost(enumeration="NotificationCategory", optional, tag="1")]
    pub category: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAllAsReadResponse {
    #[prost(uint64, tag="1")]
    pub marked_count: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DismissRequest {
    #[prost(string, tag="1")]
    pub notification_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DismissAllRequest {
    #[prost(enumeration="NotificationCategory", optional, tag="1")]
    pub category: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DismissAllResponse {
    #[prost(uint64, tag="1")]
    pub dismissed_count: u64,
}
// ============================================================================
// User preferences
// ============================================================================

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPreferencesRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPreferencesResponse {
    #[prost(message, optional, tag="1")]
    pub preferences: ::core::option::Option<NotificationPreferences>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePreferencesRequest {
    #[prost(message, optional, tag="1")]
    pub preferences: ::core::option::Option<NotificationPreferences>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePreferencesResponse {
    #[prost(message, optional, tag="1")]
    pub preferences: ::core::option::Option<NotificationPreferences>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationPreferences {
    #[prost(bool, tag="1")]
    pub push_enabled: bool,
    #[prost(bool, tag="2")]
    pub email_enabled: bool,
    #[prost(bool, tag="3")]
    pub sound_enabled: bool,
    /// Per-category settings
    #[prost(message, repeated, tag="4")]
    pub category_preferences: ::prost::alloc::vec::Vec<CategoryPreference>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CategoryPreference {
    #[prost(enumeration="NotificationCategory", tag="1")]
    pub category: i32,
    #[prost(bool, tag="2")]
    pub enabled: bool,
    #[prost(bool, tag="3")]
    pub push: bool,
    #[prost(bool, tag="4")]
    pub email: bool,
    /// Only notify above this priority
    #[prost(enumeration="NotificationPriority", tag="5")]
    pub min_priority: i32,
}
include!("notification.v1.serde.rs");
include!("notification.v1.tonic.rs");
// @@protoc_insertion_point(module)