//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::NotificationCategory;
use super::sea_orm_active_enums::NotificationPriority;
use super::sea_orm_active_enums::OriginEntityType;
use super::sea_orm_active_enums::OriginService;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "notifications")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub pid: String,
    #[sea_orm(unique_key = "idx_notifications_idempotency")]
    pub user_id: String,
    pub org_pid: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon_url: Option<String>,
    pub category: NotificationCategory,
    pub priority: NotificationPriority,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub actions: Option<Json>,
    pub origin_service: OriginService,
    pub origin_entity_type: Option<OriginEntityType>,
    pub origin_entity_pid: Option<String>,
    pub is_read: bool,
    pub read_at: Option<DateTimeWithTimeZone>,
    pub is_dismissed: bool,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique_key = "idx_notifications_idempotency")]
    pub idempotency_key: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
