// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Tool {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    /// "system" for built-in tools, "user_defined" for user-created tools
    #[prost(string, tag="4")]
    pub tool_type: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub is_active: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListToolsRequest {
    #[prost(bool, optional, tag="1")]
    pub is_active: ::core::option::Option<bool>,
    #[prost(string, optional, tag="2")]
    pub tool_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, tag="3")]
    pub page: u64,
    #[prost(uint64, tag="4")]
    pub page_size: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsResponse {
    #[prost(message, repeated, tag="1")]
    pub tools: ::prost::alloc::vec::Vec<Tool>,
    #[prost(uint64, tag="2")]
    pub total: u64,
    #[prost(uint64, tag="3")]
    pub page: u64,
    #[prost(uint64, tag="4")]
    pub page_size: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetToolRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetToolResponse {
    #[prost(message, optional, tag="1")]
    pub tool: ::core::option::Option<Tool>,
}
/// Shared config fields applicable to all agent types.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BaseAgentConfig {
    #[prost(uint32, optional, tag="1")]
    pub history_length: ::core::option::Option<u32>,
    #[prost(bool, optional, tag="2")]
    pub thinking_enabled: ::core::option::Option<bool>,
    #[prost(bool, optional, tag="3")]
    pub streaming_enabled: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag="4")]
    pub timeout_seconds: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="5")]
    pub session_ttl_seconds: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="6")]
    pub max_tokens: ::core::option::Option<u32>,
    /// Memory/embedding config
    #[prost(bool, optional, tag="7")]
    pub memory_enabled: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag="8")]
    pub memory_result_count: ::core::option::Option<u32>,
    #[prost(float, optional, tag="9")]
    pub memory_similarity_threshold: ::core::option::Option<f32>,
    #[prost(float, optional, tag="10")]
    pub compaction_threshold: ::core::option::Option<f32>,
    #[prost(float, optional, tag="11")]
    pub compaction_keep_ratio: ::core::option::Option<f32>,
    /// Document context config
    #[prost(uint32, optional, tag="12")]
    pub document_result_count: ::core::option::Option<u32>,
    /// Idle timeout: resets on every stream item (text, tool call, tool result).
    /// Fires only when the stream produces no activity for this duration.
    /// Distinct from timeout_seconds (field 4), which is a wall-clock cap.
    #[prost(uint32, optional, tag="13")]
    pub idle_timeout_seconds: ::core::option::Option<u32>,
}
/// Config specific to the Startup agent type.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartupAgentConfig {
    #[prost(bool, optional, tag="1")]
    pub use_system_providers_on_creation: ::core::option::Option<bool>,
}
/// Top-level agent config: shared base + kind-specific config.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AgentConfig {
    #[prost(message, optional, tag="1")]
    pub base: ::core::option::Option<BaseAgentConfig>,
    #[prost(oneof="agent_config::KindConfig", tags="2")]
    pub kind_config: ::core::option::Option<agent_config::KindConfig>,
}
/// Nested message and enum types in `AgentConfig`.
pub mod agent_config {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum KindConfig {
        #[prost(message, tag="2")]
        Startup(super::StartupAgentConfig),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentProvider {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentModel {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub provider: ::core::option::Option<AgentProvider>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Agent {
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub slug: ::prost::alloc::string::String,
    #[prost(enumeration="AgentKind", tag="5")]
    pub kind: i32,
    #[prost(message, optional, tag="6")]
    pub model: ::core::option::Option<AgentModel>,
    #[prost(int32, tag="7")]
    pub temperature: i32,
    #[prost(string, tag="9")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub tools: ::prost::alloc::vec::Vec<Tool>,
    #[prost(message, optional, tag="11")]
    pub config: ::core::option::Option<AgentConfig>,
    #[prost(bool, tag="13")]
    pub is_active: bool,
    #[prost(string, tag="15")]
    pub created_by_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(oneof="agent::Identifier", tags="1, 2")]
    pub identifier: ::core::option::Option<agent::Identifier>,
}
/// Nested message and enum types in `Agent`.
pub mod agent {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int32, tag="1")]
        Id(i32),
        #[prost(string, tag="2")]
        Pid(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAgentsRequest {
    #[prost(string, optional, tag="1")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="2")]
    pub is_active: ::core::option::Option<bool>,
    #[prost(string, optional, tag="3")]
    pub provider_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="4")]
    pub page: i32,
    #[prost(int32, tag="5")]
    pub page_size: i32,
    /// When false, excludes agents that are linked as user assistants
    #[prost(bool, optional, tag="6")]
    pub with_assistants: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAgentsResponse {
    #[prost(message, repeated, tag="1")]
    pub agents: ::prost::alloc::vec::Vec<Agent>,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAgentRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAgentResponse {
    #[prost(message, optional, tag="1")]
    pub agent: ::core::option::Option<Agent>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateAgentRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model_pid: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub temperature: i32,
    #[prost(string, tag="4")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub config: ::core::option::Option<AgentConfig>,
    #[prost(string, optional, tag="6")]
    pub provider_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="7")]
    pub tool_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration="AgentKind", tag="8")]
    pub kind: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateAgentResponse {
    #[prost(message, optional, tag="1")]
    pub agent: ::core::option::Option<Agent>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateAgentToolRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub is_active: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAgentRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub slug: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub model_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="5")]
    pub temperature: ::core::option::Option<i32>,
    #[prost(string, optional, tag="6")]
    pub system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="7")]
    pub config: ::core::option::Option<AgentConfig>,
    #[prost(string, optional, tag="8")]
    pub provider_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="9")]
    pub tools: ::prost::alloc::vec::Vec<UpdateAgentToolRequest>,
    #[prost(bool, optional, tag="10")]
    pub is_active: ::core::option::Option<bool>,
    #[prost(enumeration="AgentKind", optional, tag="11")]
    pub kind: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateAgentResponse {
    #[prost(message, optional, tag="1")]
    pub agent: ::core::option::Option<Agent>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAgentRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAgentResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserAssistantRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserAssistantResponse {
    #[prost(message, optional, tag="1")]
    pub agent: ::core::option::Option<Agent>,
}
// --- Sharing ---

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentShare {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    /// bitfield: 1=read, 2=write, 4=execute
    #[prost(int32, tag="2")]
    pub permissions: i32,
    #[prost(string, tag="3")]
    pub shared_by: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub email: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareAgentRequest {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    /// recipient
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// bitfield
    #[prost(int32, tag="3")]
    pub permissions: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareAgentResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnshareAgentRequest {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    /// recipient to revoke
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnshareAgentResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAgentSharesRequest {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub page_size: i32,
    #[prost(string, optional, tag="3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAgentSharesResponse {
    #[prost(message, repeated, tag="1")]
    pub shares: ::prost::alloc::vec::Vec<AgentShare>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub total: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentKind {
    Unspecified = 0,
    Startup = 1,
    Ephemeral = 2,
}
impl AgentKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGENT_KIND_UNSPECIFIED",
            Self::Startup => "AGENT_KIND_STARTUP",
            Self::Ephemeral => "AGENT_KIND_EPHEMERAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGENT_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "AGENT_KIND_STARTUP" => Some(Self::Startup),
            "AGENT_KIND_EPHEMERAL" => Some(Self::Ephemeral),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Document {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(int64, tag="4")]
    pub size_bytes: i64,
    #[prost(string, optional, tag="5")]
    pub summary: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="DocumentStatus", tag="6")]
    pub status: i32,
    #[prost(string, optional, tag="7")]
    pub error_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="8")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DocumentGroup {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="4")]
    pub is_org_shared: bool,
    #[prost(int32, tag="5")]
    pub document_count: i32,
    #[prost(string, tag="6")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DocumentChunk {
    #[prost(string, tag="1")]
    pub document_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub chunk_index: i32,
    #[prost(string, tag="4")]
    pub text: ::prost::alloc::string::String,
    #[prost(float, tag="5")]
    pub score: f32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadDocumentRequest {
    #[prost(string, tag="1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(bytes="bytes", tag="3")]
    pub content: ::prost::bytes::Bytes,
    #[prost(string, optional, tag="4")]
    pub conversation_pid: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadDocumentResponse {
    #[prost(message, optional, tag="1")]
    pub document: ::core::option::Option<Document>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDocumentRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDocumentResponse {
    #[prost(message, optional, tag="1")]
    pub document: ::core::option::Option<Document>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDocumentsRequest {
    #[prost(string, optional, tag="1")]
    pub group_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="DocumentStatus", optional, tag="2")]
    pub status: ::core::option::Option<i32>,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDocumentsResponse {
    #[prost(message, repeated, tag="1")]
    pub documents: ::prost::alloc::vec::Vec<Document>,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteDocumentRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteDocumentResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDocumentRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub filename: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDocumentResponse {
    #[prost(message, optional, tag="1")]
    pub document: ::core::option::Option<Document>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDownloadUrlRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDownloadUrlResponse {
    #[prost(string, tag="1")]
    pub download_url: ::prost::alloc::string::String,
}
// =============================================================================
// DocumentGroupService messages
// =============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateGroupRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="3")]
    pub is_org_shared: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateGroupResponse {
    #[prost(message, optional, tag="1")]
    pub group: ::core::option::Option<DocumentGroup>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGroupRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetGroupResponse {
    #[prost(message, optional, tag="1")]
    pub group: ::core::option::Option<DocumentGroup>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListGroupsRequest {
    #[prost(int32, tag="1")]
    pub page: i32,
    #[prost(int32, tag="2")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListGroupsResponse {
    #[prost(message, repeated, tag="1")]
    pub groups: ::prost::alloc::vec::Vec<DocumentGroup>,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteGroupRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteGroupResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateGroupRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="4")]
    pub is_org_shared: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateGroupResponse {
    #[prost(message, optional, tag="1")]
    pub group: ::core::option::Option<DocumentGroup>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddDocumentsToGroupRequest {
    #[prost(string, tag="1")]
    pub group_pid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub document_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddDocumentsToGroupResponse {
    #[prost(message, optional, tag="1")]
    pub group: ::core::option::Option<DocumentGroup>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveDocumentsFromGroupRequest {
    #[prost(string, tag="1")]
    pub group_pid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub document_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveDocumentsFromGroupResponse {
    #[prost(message, optional, tag="1")]
    pub group: ::core::option::Option<DocumentGroup>,
}
// =============================================================================
// DocumentSearchService messages
// =============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchDocumentsRequest {
    #[prost(string, tag="1")]
    pub query: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub group_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="3")]
    pub top_n: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub top_k: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchDocumentsResponse {
    #[prost(message, repeated, tag="1")]
    pub results: ::prost::alloc::vec::Vec<SearchResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResult {
    #[prost(message, optional, tag="1")]
    pub document: ::core::option::Option<Document>,
    #[prost(message, repeated, tag="2")]
    pub chunks: ::prost::alloc::vec::Vec<DocumentChunk>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SearchChunksRequest {
    #[prost(string, tag="1")]
    pub query: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="2")]
    pub top_k: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchChunksResponse {
    #[prost(message, repeated, tag="1")]
    pub chunks: ::prost::alloc::vec::Vec<DocumentChunk>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DocumentStatus {
    Unspecified = 0,
    Pending = 1,
    Processing = 2,
    Ready = 3,
    Failed = 4,
}
impl DocumentStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DOCUMENT_STATUS_UNSPECIFIED",
            Self::Pending => "DOCUMENT_STATUS_PENDING",
            Self::Processing => "DOCUMENT_STATUS_PROCESSING",
            Self::Ready => "DOCUMENT_STATUS_READY",
            Self::Failed => "DOCUMENT_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DOCUMENT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "DOCUMENT_STATUS_PENDING" => Some(Self::Pending),
            "DOCUMENT_STATUS_PROCESSING" => Some(Self::Processing),
            "DOCUMENT_STATUS_READY" => Some(Self::Ready),
            "DOCUMENT_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// ToolCall represents an invocation of a tool
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolCall {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub arguments: ::core::option::Option<::pbjson_types::Struct>,
    #[prost(enumeration="ToolExecutionStatus", tag="4")]
    pub status: i32,
}
/// ToolResult represents the output of a tool call
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolResult {
    #[prost(string, tag="1")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub result: ::prost::alloc::string::String,
    #[prost(enumeration="ToolExecutionStatus", tag="3")]
    pub status: i32,
}
/// MediaContent represents image, audio, video, or document data
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MediaContent {
    /// MIME type: "image/png", "audio/mp3", etc.
    #[prost(string, optional, tag="4")]
    pub media_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof="media_content::Source", tags="1, 2, 3")]
    pub source: ::core::option::Option<media_content::Source>,
}
/// Nested message and enum types in `MediaContent`.
pub mod media_content {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Source {
        /// URL/URI to the media
        #[prost(string, tag="1")]
        Url(::prost::alloc::string::String),
        /// Raw binary data
        #[prost(bytes, tag="2")]
        Data(::prost::bytes::Bytes),
        /// Base64-encoded string
        #[prost(string, tag="3")]
        Base64(::prost::alloc::string::String),
    }
}
/// MessagePart represents a single part of a message (text, thinking, tool_call, tool_result, media)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePart {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration="MessagePartKind", tag="2")]
    pub kind: i32,
    #[prost(enumeration="MessagePartStatus", tag="3")]
    pub status: i32,
    #[prost(string, optional, tag="4")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="5")]
    pub tool_call: ::core::option::Option<ToolCall>,
    #[prost(message, optional, tag="6")]
    pub tool_result: ::core::option::Option<ToolResult>,
    /// For IMAGE, AUDIO, VIDEO, DOCUMENT kinds
    #[prost(message, optional, tag="7")]
    pub media: ::core::option::Option<MediaContent>,
    /// Document summary (for DOCUMENT kind)
    #[prost(string, optional, tag="8")]
    pub summary: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub role: ::prost::alloc::string::String,
    #[prost(enumeration="MessageStatus", tag="3")]
    pub status: i32,
    #[prost(message, repeated, tag="7")]
    pub parts: ::prost::alloc::vec::Vec<MessagePart>,
    #[prost(string, tag="8")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conversation {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub agent_pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="4")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="5")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(int32, tag="6")]
    pub message_count: i32,
    #[prost(string, optional, tag="7")]
    pub last_message_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="9")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InferRequest {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub conversation_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="5")]
    pub document_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Streaming response events - follows SSE pattern: part_start, part_delta, part_end
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferResponse {
    #[prost(oneof="infer_response::Event", tags="1, 2, 3, 4, 5, 6, 7")]
    pub event: ::core::option::Option<infer_response::Event>,
}
/// Nested message and enum types in `InferResponse`.
pub mod infer_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag="1")]
        PartStart(super::PartStart),
        #[prost(message, tag="2")]
        PartDelta(super::PartDelta),
        #[prost(message, tag="3")]
        PartEnd(super::PartEnd),
        #[prost(message, tag="4")]
        ToolStatus(super::ToolStatus),
        #[prost(message, tag="5")]
        Complete(super::InferenceComplete),
        #[prost(message, tag="6")]
        Cancelled(super::InferenceCancelled),
        #[prost(message, tag="7")]
        Acknowledged(super::MessageAcknowledged),
    }
}
/// Signals that the user message has been persisted to the database.
/// Emitted before inference begins.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MessageAcknowledged {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message_pid: ::prost::alloc::string::String,
}
/// Signals that inference was cancelled by user request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InferenceCancelled {
    #[prost(string, tag="1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelInferenceRequest {
    #[prost(string, tag="1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub conversation_pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelInferenceResponse {
    #[prost(bool, tag="1")]
    pub cancelled: bool,
}
/// Signals the start of a new message part
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartStart {
    #[prost(string, tag="1")]
    pub part_id: ::prost::alloc::string::String,
    #[prost(enumeration="MessagePartKind", tag="2")]
    pub kind: i32,
    #[prost(string, optional, tag="3")]
    pub tool_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub tool_call_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// Streaming content delta for a part
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PartDelta {
    #[prost(string, tag="1")]
    pub part_id: ::prost::alloc::string::String,
    #[prost(enumeration="MessagePartKind", tag="2")]
    pub kind: i32,
    #[prost(oneof="part_delta::Delta", tags="3, 4, 5")]
    pub delta: ::core::option::Option<part_delta::Delta>,
}
/// Nested message and enum types in `PartDelta`.
pub mod part_delta {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Delta {
        #[prost(string, tag="3")]
        Content(::prost::alloc::string::String),
        #[prost(message, tag="4")]
        Arguments(::pbjson_types::Struct),
        /// For IMAGE, AUDIO, VIDEO, DOCUMENT (typically sent complete, not streamed)
        #[prost(message, tag="5")]
        Media(super::MediaContent),
    }
}
/// Signals the end of a message part
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PartEnd {
    #[prost(string, tag="1")]
    pub part_id: ::prost::alloc::string::String,
    #[prost(enumeration="MessagePartStatus", tag="2")]
    pub status: i32,
}
/// Tool execution status update (emitted via rig prompt hooks)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToolStatus {
    #[prost(string, tag="1")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(enumeration="ToolExecutionStatus", tag="2")]
    pub status: i32,
    #[prost(string, optional, tag="3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
/// Inference completed - final summary
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceComplete {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub message: ::core::option::Option<Message>,
    #[prost(message, optional, tag="4")]
    pub metadata: ::core::option::Option<::pbjson_types::Struct>,
}
/// Synchronous inference response - complete response in one message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferSyncResponse {
    #[prost(string, tag="1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub conversation_pid: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub message_pid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub message: ::core::option::Option<Message>,
    #[prost(message, optional, tag="5")]
    pub metadata: ::core::option::Option<::pbjson_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConversationsRequest {
    #[prost(bool, optional, tag="1")]
    pub is_active: ::core::option::Option<bool>,
    #[prost(string, optional, tag="2")]
    pub agent_pid: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConversationsResponse {
    #[prost(message, repeated, tag="1")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConversationRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationResponse {
    #[prost(message, optional, tag="1")]
    pub conversation: ::core::option::Option<Conversation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConversationRequest {
    #[prost(string, tag="1")]
    pub agent_pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateConversationResponse {
    #[prost(message, optional, tag="1")]
    pub conversation: ::core::option::Option<Conversation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConversationRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConversationResponse {
}
// =============================================================================
// Conversation-Document management
// =============================================================================

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AttachDocumentsRequest {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub document_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AttachDocumentsResponse {
    #[prost(int32, tag="1")]
    pub attached_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DetachDocumentsRequest {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="2")]
    pub document_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DetachDocumentsResponse {
    #[prost(int32, tag="1")]
    pub detached_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConversationDocumentsRequest {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConversationDocumentsResponse {
    #[prost(message, repeated, tag="1")]
    pub documents: ::prost::alloc::vec::Vec<Document>,
}
// --- Sharing ---

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationShare {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    /// bitfield: 1=read, 2=write, 4=execute
    #[prost(int32, tag="2")]
    pub permissions: i32,
    #[prost(string, tag="3")]
    pub shared_by: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub email: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareConversationRequest {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    /// recipient
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    /// bitfield
    #[prost(int32, tag="3")]
    pub permissions: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareConversationResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnshareConversationRequest {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    /// recipient to revoke
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnshareConversationResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConversationSharesRequest {
    #[prost(string, tag="1")]
    pub conversation_pid: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub page_size: i32,
    #[prost(string, optional, tag="3")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConversationSharesResponse {
    #[prost(message, repeated, tag="1")]
    pub shares: ::prost::alloc::vec::Vec<ConversationShare>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="3")]
    pub total: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessagePartKind {
    Unspecified = 0,
    Text = 1,
    Thinking = 2,
    ToolCall = 3,
    ToolResult = 4,
    Image = 5,
    Audio = 6,
    Video = 7,
    Document = 8,
    Metadata = 9,
}
impl MessagePartKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_PART_KIND_UNSPECIFIED",
            Self::Text => "MESSAGE_PART_KIND_TEXT",
            Self::Thinking => "MESSAGE_PART_KIND_THINKING",
            Self::ToolCall => "MESSAGE_PART_KIND_TOOL_CALL",
            Self::ToolResult => "MESSAGE_PART_KIND_TOOL_RESULT",
            Self::Image => "MESSAGE_PART_KIND_IMAGE",
            Self::Audio => "MESSAGE_PART_KIND_AUDIO",
            Self::Video => "MESSAGE_PART_KIND_VIDEO",
            Self::Document => "MESSAGE_PART_KIND_DOCUMENT",
            Self::Metadata => "MESSAGE_PART_KIND_METADATA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_PART_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_PART_KIND_TEXT" => Some(Self::Text),
            "MESSAGE_PART_KIND_THINKING" => Some(Self::Thinking),
            "MESSAGE_PART_KIND_TOOL_CALL" => Some(Self::ToolCall),
            "MESSAGE_PART_KIND_TOOL_RESULT" => Some(Self::ToolResult),
            "MESSAGE_PART_KIND_IMAGE" => Some(Self::Image),
            "MESSAGE_PART_KIND_AUDIO" => Some(Self::Audio),
            "MESSAGE_PART_KIND_VIDEO" => Some(Self::Video),
            "MESSAGE_PART_KIND_DOCUMENT" => Some(Self::Document),
            "MESSAGE_PART_KIND_METADATA" => Some(Self::Metadata),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessagePartStatus {
    Unspecified = 0,
    Pending = 1,
    Streaming = 2,
    Complete = 3,
    Failed = 4,
}
impl MessagePartStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_PART_STATUS_UNSPECIFIED",
            Self::Pending => "MESSAGE_PART_STATUS_PENDING",
            Self::Streaming => "MESSAGE_PART_STATUS_STREAMING",
            Self::Complete => "MESSAGE_PART_STATUS_COMPLETE",
            Self::Failed => "MESSAGE_PART_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_PART_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_PART_STATUS_PENDING" => Some(Self::Pending),
            "MESSAGE_PART_STATUS_STREAMING" => Some(Self::Streaming),
            "MESSAGE_PART_STATUS_COMPLETE" => Some(Self::Complete),
            "MESSAGE_PART_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// MessageStatus - overall status of a message (not individual parts)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageStatus {
    Unspecified = 0,
    Complete = 1,
    Cancelled = 2,
    Error = 3,
}
impl MessageStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MESSAGE_STATUS_UNSPECIFIED",
            Self::Complete => "MESSAGE_STATUS_COMPLETE",
            Self::Cancelled => "MESSAGE_STATUS_CANCELLED",
            Self::Error => "MESSAGE_STATUS_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MESSAGE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MESSAGE_STATUS_COMPLETE" => Some(Self::Complete),
            "MESSAGE_STATUS_CANCELLED" => Some(Self::Cancelled),
            "MESSAGE_STATUS_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
/// Tool execution status - for tracking tool call lifecycle
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ToolExecutionStatus {
    Unspecified = 0,
    Calling = 1,
    Running = 2,
    Completed = 3,
    Failed = 4,
}
impl ToolExecutionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TOOL_EXECUTION_STATUS_UNSPECIFIED",
            Self::Calling => "TOOL_EXECUTION_STATUS_CALLING",
            Self::Running => "TOOL_EXECUTION_STATUS_RUNNING",
            Self::Completed => "TOOL_EXECUTION_STATUS_COMPLETED",
            Self::Failed => "TOOL_EXECUTION_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOOL_EXECUTION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "TOOL_EXECUTION_STATUS_CALLING" => Some(Self::Calling),
            "TOOL_EXECUTION_STATUS_RUNNING" => Some(Self::Running),
            "TOOL_EXECUTION_STATUS_COMPLETED" => Some(Self::Completed),
            "TOOL_EXECUTION_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provider {
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub provider_type: ::prost::alloc::string::String,
    #[prost(enumeration="ProviderSource", tag="5")]
    pub source: i32,
    #[prost(string, optional, tag="6")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="7")]
    pub config: ::core::option::Option<::pbjson_types::Struct>,
    #[prost(string, tag="8")]
    pub credentials: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub endpoint_url: ::prost::alloc::string::String,
    #[prost(bool, tag="10")]
    pub is_active: bool,
    #[prost(string, tag="11")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(oneof="provider::Identifier", tags="1, 2")]
    pub identifier: ::core::option::Option<provider::Identifier>,
}
/// Nested message and enum types in `Provider`.
pub mod provider {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int32, tag="1")]
        Id(i32),
        #[prost(string, tag="2")]
        Pid(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListProvidersRequest {
    #[prost(bool, optional, tag="1")]
    pub is_active: ::core::option::Option<bool>,
    #[prost(enumeration="ProviderSource", optional, tag="2")]
    pub source: ::core::option::Option<i32>,
    #[prost(string, optional, tag="3")]
    pub provider_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="5")]
    pub page: i32,
    #[prost(int32, tag="6")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProvidersResponse {
    #[prost(message, repeated, tag="1")]
    pub providers: ::prost::alloc::vec::Vec<Provider>,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProviderRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProviderResponse {
    #[prost(message, optional, tag="1")]
    pub provider: ::core::option::Option<Provider>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProviderRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub provider_type: ::prost::alloc::string::String,
    #[prost(enumeration="ProviderSource", tag="3")]
    pub source: i32,
    #[prost(message, optional, tag="4")]
    pub config: ::core::option::Option<::pbjson_types::Struct>,
    #[prost(string, tag="5")]
    pub credentials: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub endpoint_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProviderResponse {
    #[prost(message, optional, tag="1")]
    pub provider: ::core::option::Option<Provider>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProviderRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub provider_type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="4")]
    pub config: ::core::option::Option<::pbjson_types::Struct>,
    #[prost(string, optional, tag="5")]
    pub credentials: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub endpoint_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="7")]
    pub is_active: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProviderResponse {
    #[prost(message, optional, tag="1")]
    pub provider: ::core::option::Option<Provider>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProviderRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProviderResponse {
}
// =============================================================================
// Model messages
// =============================================================================

/// Capabilities that a model may support
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelCapabilities {
    /// Can process images
    #[prost(bool, tag="1")]
    pub vision: bool,
    /// Supports tool/function calls
    #[prost(bool, tag="2")]
    pub function_calling: bool,
    /// Can output structured JSON
    #[prost(bool, tag="3")]
    pub json_mode: bool,
    /// Supports streaming responses
    #[prost(bool, tag="4")]
    pub streaming: bool,
    /// Supports system/preamble messages
    #[prost(bool, tag="5")]
    pub system_prompt: bool,
    /// Supports multi-turn conversations
    #[prost(bool, tag="6")]
    pub multi_turn: bool,
    /// Supports extended thinking/reasoning
    #[prost(bool, tag="7")]
    pub thinking: bool,
}
/// Provider-specific metadata
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelMetadata {
    /// OpenAI: organization that owns the model
    #[prost(string, optional, tag="1")]
    pub owned_by: ::core::option::Option<::prost::alloc::string::String>,
    /// Model family (e.g., "gpt-4", "claude-3")
    #[prost(string, optional, tag="2")]
    pub family: ::core::option::Option<::prost::alloc::string::String>,
    /// Cost per million input tokens (microdollars)
    #[prost(int64, optional, tag="3")]
    pub input_cost_per_mtok: ::core::option::Option<i64>,
    /// Cost per million output tokens (microdollars)
    #[prost(int64, optional, tag="4")]
    pub output_cost_per_mtok: ::core::option::Option<i64>,
    /// Maximum tokens model can generate
    #[prost(int64, optional, tag="5")]
    pub max_output_tokens: ::core::option::Option<i64>,
    /// Ollama: quantization level (e.g., "Q4_0")
    #[prost(string, optional, tag="6")]
    pub quantization: ::core::option::Option<::prost::alloc::string::String>,
    /// Ollama: model size on disk
    #[prost(int64, optional, tag="7")]
    pub size_bytes: ::core::option::Option<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Model {
    /// Provider's model identifier (e.g., "gpt-4o", "claude-3-opus-20240229")
    #[prost(string, tag="3")]
    pub model_id: ::prost::alloc::string::String,
    /// Display name
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    /// FK to Provider
    #[prost(string, tag="5")]
    pub provider_pid: ::prost::alloc::string::String,
    /// Denormalized: "openai", "anthropic", etc.
    #[prost(string, tag="6")]
    pub provider_type: ::prost::alloc::string::String,
    /// Denormalized: Provider's display name
    #[prost(string, tag="7")]
    pub provider_name: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="8")]
    pub context_length: ::core::option::Option<i32>,
    #[prost(message, optional, tag="9")]
    pub capabilities: ::core::option::Option<ModelCapabilities>,
    #[prost(message, optional, tag="10")]
    pub metadata: ::core::option::Option<ModelMetadata>,
    #[prost(bool, tag="11")]
    pub is_active: bool,
    /// If present, model is deprecated
    #[prost(string, optional, tag="12")]
    pub deprecation_message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="13")]
    pub last_fetched_at: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="14")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(oneof="model::Identifier", tags="1, 2")]
    pub identifier: ::core::option::Option<model::Identifier>,
}
/// Nested message and enum types in `Model`.
pub mod model {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Identifier {
        #[prost(int32, tag="1")]
        Id(i32),
        #[prost(string, tag="2")]
        Pid(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModelsRequest {
    /// Filter by provider
    #[prost(string, optional, tag="1")]
    pub provider_pid: ::core::option::Option<::prost::alloc::string::String>,
    /// Filter by provider type (e.g., "openai")
    #[prost(string, optional, tag="2")]
    pub provider_type: ::core::option::Option<::prost::alloc::string::String>,
    /// Filter by active status
    #[prost(bool, optional, tag="3")]
    pub is_active: ::core::option::Option<bool>,
    /// Include deprecated models (default: false)
    #[prost(bool, optional, tag="4")]
    pub include_deprecated: ::core::option::Option<bool>,
    #[prost(int32, tag="5")]
    pub page: i32,
    #[prost(int32, tag="6")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag="1")]
    pub models: ::prost::alloc::vec::Vec<Model>,
    #[prost(int32, tag="2")]
    pub total: i32,
    #[prost(int32, tag="3")]
    pub page: i32,
    #[prost(int32, tag="4")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetModelResponse {
    #[prost(message, optional, tag="1")]
    pub model: ::core::option::Option<Model>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshProviderModelsRequest {
    /// If set, refresh only this provider; if empty, refresh all accessible providers
    #[prost(string, optional, tag="1")]
    pub provider_pid: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshProviderModelsResponse {
    /// Number of providers queued for refresh
    #[prost(int32, tag="1")]
    pub providers_queued: i32,
    /// PIDs of providers being refreshed
    #[prost(string, repeated, tag="2")]
    pub provider_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProviderSource {
    Unspecified = 0,
    System = 1,
    User = 2,
}
impl ProviderSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROVIDER_SOURCE_UNSPECIFIED",
            Self::System => "PROVIDER_SOURCE_SYSTEM",
            Self::User => "PROVIDER_SOURCE_USER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROVIDER_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "PROVIDER_SOURCE_SYSTEM" => Some(Self::System),
            "PROVIDER_SOURCE_USER" => Some(Self::User),
            _ => None,
        }
    }
}
include!("rig.v1.serde.rs");
include!("rig.v1.tonic.rs");
// @@protoc_insertion_point(module)