// @generated
// This file is @generated by prost-build.
/// FailedJob mirrors `memoir_core::jobs::FailedJob` exactly. Deliberately
/// excludes the original `payload` and any content from the referenced
/// memory — see the service-level PII boundary in AdminService's doc
/// comment.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FailedJob {
    #[prost(int64, tag="1")]
    pub id: i64,
    /// The memory pid this job processes.
    #[prost(string, tag="2")]
    pub source_pid: ::prost::alloc::string::String,
    #[prost(enumeration="JobKind", tag="3")]
    pub kind: i32,
    #[prost(int32, tag="4")]
    pub attempts: i32,
    #[prost(string, optional, tag="5")]
    pub failure_reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="6")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
// ─── ListFailedJobs RPC ─────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFailedJobsRequest {
    /// Maximum rows to return. `limit = 0` means "use library default" (the
    /// implementer maps to whatever cap `Client::failed_jobs` accepts at
    /// ticket-time). Pagination is limit-only in v0.1 — no cursor.
    #[prost(int32, tag="1")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListFailedJobsResponse {
    #[prost(message, repeated, tag="1")]
    pub jobs: ::prost::alloc::vec::Vec<FailedJob>,
}
// ─── PendingJobsCount RPC ───────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PendingJobsCountRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PendingJobsCountResponse {
    /// Number of jobs currently in `pending` state. Library returns `u64`;
    /// wire is `int64` for TS-compat (JS `number` is f64, safe to 2^53-1).
    #[prost(int64, tag="1")]
    pub count: i64,
}
// ─── RetryJob RPC ───────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryJobRequest {
    #[prost(int64, tag="1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryJobResponse {
}
// ─── DeleteFailedJob RPC ────────────────────────────────────────────────────

/// No `hard_delete` flag: the library's `Client::delete_failed_job` is
/// unconditional. The referenced memory row is untouched either way.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFailedJobRequest {
    #[prost(int64, tag="1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFailedJobResponse {
}
// ─── RetryFailedJobs (bulk) RPC ─────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryFailedJobsRequest {
    /// When set, only retry jobs of this kind. Unset = retry all kinds.
    #[prost(enumeration="JobKind", optional, tag="1")]
    pub of_kind: ::core::option::Option<i32>,
    /// When true, return the affected count without touching any rows.
    #[prost(bool, tag="2")]
    pub dry_run: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryFailedJobsResponse {
    /// Number of jobs the operation affected (or, in `dry_run` mode, would
    /// have affected). Mirrors `RetryBuilder`'s `u64` return.
    #[prost(int64, tag="1")]
    pub affected: i64,
    /// Echo of the request's `dry_run` for caller clarity — confirms that the
    /// count reflects a preview, not a real retry.
    #[prost(bool, tag="2")]
    pub dry_run: bool,
}
// ─── Unsupersede RPC ────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsupersedeRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsupersedeResponse {
}
// ─── Reconcile RPC ──────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReconcileRequest {
    /// When true, run only the failed-row retry pass; skip orphan cleanup.
    #[prost(bool, tag="1")]
    pub only_retry_failed: bool,
    /// When true, run only the orphan-cleanup pass; skip retry. Set BOTH
    /// flags to false (or omit both) to run both passes.
    #[prost(bool, tag="2")]
    pub only_clean_orphans: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReconcileResponse {
    /// Mirrors `memoir_core::client::ReconcileSummary`. Counts reflect work
    /// performed, not work attempted — see the library docs.
    ///
    /// Rows the retry pass attempted to re-embed.
    #[prost(int64, tag="1")]
    pub failed_retried: i64,
    /// Rows the retry pass moved into `indexed`.
    #[prost(int64, tag="2")]
    pub failed_recovered: i64,
    /// Orphan vectors deleted from the index.
    #[prost(int64, tag="3")]
    pub orphans_deleted: i64,
}
// ─── Core types ─────────────────────────────────────────────────────────────

/// JobKind mirrors `memoir_core::jobs::JobKind`. The set is closed by the
/// CHECK constraint on `memory_jobs.kind`; extending it requires a
/// follow-up library migration first, then a proto bump.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobKind {
    Unspecified = 0,
    /// Embed a memory's content + upsert its vector.
    Embed = 1,
    /// Run LLM extraction against an episodic memory.
    Extract = 2,
}
impl JobKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOB_KIND_UNSPECIFIED",
            Self::Embed => "JOB_KIND_EMBED",
            Self::Extract => "JOB_KIND_EXTRACT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_KIND_EMBED" => Some(Self::Embed),
            "JOB_KIND_EXTRACT" => Some(Self::Extract),
            _ => None,
        }
    }
}
// ─── Core types ─────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_admin: bool,
    #[prost(message, optional, tag="4")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="5")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
/// ApiKey carries everything *except* the secret. The secret is returned only
/// in CreateApiKeyResponse and RotateApiKeyResponse; Get/List never include it.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApiKey {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    /// The lookup half of `mk.<key_id>.<secret>`. Non-secret.
    #[prost(string, tag="2")]
    pub key_id: ::prost::alloc::string::String,
    /// Human-readable label set at creation, e.g. "ci-runner".
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="ApiKeyRole", tag="4")]
    pub role: i32,
    /// When set, the key is scope-bound to this org.
    #[prost(string, optional, tag="5")]
    pub org_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ApiKeyStatus", tag="6")]
    pub status: i32,
    #[prost(message, optional, tag="7")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="8")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag="9")]
    pub last_used_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
// ─── Bootstrap RPC ──────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsumeBootstrapTokenRequest {
    /// The plaintext token logged to stdout on first start.
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConsumeBootstrapTokenResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<User>,
}
// ─── Session RPCs ───────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag="1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    /// Short-lived JWT presented as `authorization: Bearer <access_token>` on
    /// subsequent RPCs. TTL is server-configured (default 15 minutes).
    #[prost(string, tag="1")]
    pub access_token: ::prost::alloc::string::String,
    /// Long-lived JWT exchanged via RefreshToken when the access token expires.
    /// Audience-bound to refresh use; rejected by the authenticate middleware.
    /// TTL is server-configured (default 7 days).
    #[prost(string, tag="2")]
    pub refresh_token: ::prost::alloc::string::String,
    /// Convenience copy of the authenticated user. Saves a follow-up GetUser
    /// call on a successful login.
    #[prost(message, optional, tag="3")]
    pub user: ::core::option::Option<User>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshTokenRequest {
    #[prost(string, tag="1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RefreshTokenResponse {
    /// A freshly-minted access JWT. The refresh token is unchanged — clients
    /// continue to use the original until it expires.
    #[prost(string, tag="1")]
    pub access_token: ::prost::alloc::string::String,
}
// ─── User RPCs ──────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateUserRequest {
    #[prost(string, tag="1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub is_admin: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateUserResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<User>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<User>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListUsersRequest {
    #[prost(int32, tag="1")]
    pub limit: i32,
    #[prost(string, optional, tag="2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersResponse {
    #[prost(message, repeated, tag="1")]
    pub users: ::prost::alloc::vec::Vec<User>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteUserRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteUserResponse {
}
// ─── API key RPCs ───────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateApiKeyRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="ApiKeyRole", tag="2")]
    pub role: i32,
    #[prost(string, optional, tag="3")]
    pub org_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateApiKeyResponse {
    #[prost(message, optional, tag="1")]
    pub key: ::core::option::Option<ApiKey>,
    /// The full `mk.<key_id>.<secret>` string. Shown ONCE.
    #[prost(string, tag="2")]
    pub plaintext: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetApiKeyRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetApiKeyResponse {
    #[prost(message, optional, tag="1")]
    pub key: ::core::option::Option<ApiKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListApiKeysRequest {
    #[prost(int32, tag="1")]
    pub limit: i32,
    #[prost(string, optional, tag="2")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration="ApiKeyStatus", optional, tag="3")]
    pub status: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListApiKeysResponse {
    #[prost(message, repeated, tag="1")]
    pub keys: ::prost::alloc::vec::Vec<ApiKey>,
    #[prost(string, optional, tag="2")]
    pub next_cursor: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateApiKeyRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateApiKeyResponse {
    #[prost(message, optional, tag="1")]
    pub key: ::core::option::Option<ApiKey>,
    /// The new `mk.<key_id>.<secret>` string. Shown ONCE.
    #[prost(string, tag="2")]
    pub plaintext: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeApiKeyRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeApiKeyResponse {
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ApiKeyRole {
    Unspecified = 0,
    Admin = 1,
    Integration = 2,
}
impl ApiKeyRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "API_KEY_ROLE_UNSPECIFIED",
            Self::Admin => "API_KEY_ROLE_ADMIN",
            Self::Integration => "API_KEY_ROLE_INTEGRATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "API_KEY_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "API_KEY_ROLE_ADMIN" => Some(Self::Admin),
            "API_KEY_ROLE_INTEGRATION" => Some(Self::Integration),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ApiKeyStatus {
    Unspecified = 0,
    Active = 1,
    Revoked = 2,
}
impl ApiKeyStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "API_KEY_STATUS_UNSPECIFIED",
            Self::Active => "API_KEY_STATUS_ACTIVE",
            Self::Revoked => "API_KEY_STATUS_REVOKED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "API_KEY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "API_KEY_STATUS_ACTIVE" => Some(Self::Active),
            "API_KEY_STATUS_REVOKED" => Some(Self::Revoked),
            _ => None,
        }
    }
}
// ─── Scope ──────────────────────────────────────────────────────────────────

/// Scope uniquely identifies a memory partition. Memories written under one
/// scope are never returned under another. The triple matches the manifesto's
/// SDK pseudocode and the Tier-1 integration shape.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Scope {
    #[prost(string, tag="1")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
}
// ─── Core type ──────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Memory {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(string, tag="3")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub metadata: ::core::option::Option<::pbjson_types::Struct>,
    #[prost(message, optional, tag="5")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Set when the worker has fully processed the memory (embedding + any
    /// extraction). As of memoir-core v0.1 the library does not yet populate
    /// a dedicated `processed_at` column — the field stays unset for now;
    /// consumers should rely on `status == MEMORY_STATUS_PROCESSED` as the
    /// canonical "ready" signal. The proto field is preserved so a future
    /// library schema migration can backfill it without a proto bump.
    #[prost(message, optional, tag="6")]
    pub processed_at: ::core::option::Option<::pbjson_types::Timestamp>,
    /// Lifecycle state. Maps from memoir-core's `memories.qdrant_status`
    /// column (`pending` / `indexed` / `failed`) to PENDING / PROCESSED /
    /// FAILED at the handler boundary.
    #[prost(enumeration="MemoryStatus", tag="7")]
    pub status: i32,
}
/// Search result with similarity score attached.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchHit {
    #[prost(message, optional, tag="1")]
    pub memory: ::core::option::Option<Memory>,
    /// Cosine similarity, higher = closer. Range \[-1.0, 1.0\]; in practice
    /// memoir-core's embedding model yields scores in \[0.0, 1.0\] for typical
    /// semantic content. memoir-core's vector index returns this value
    /// verbatim (no rank normalization), sourced from Qdrant's `query`
    /// response per `packages/memoir-core/src/vector/qdrant.rs`.
    #[prost(float, tag="2")]
    pub score: f32,
}
// ─── RPCs ───────────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchRequest {
    #[prost(message, optional, tag="1")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(string, tag="2")]
    pub query: ::prost::alloc::string::String,
    /// Maximum hits to return. memoir-core treats `limit = 0` as "use library
    /// default" (currently 10, per `packages/memoir-core/src/client/search.rs`
    /// `DEFAULT_LIMIT`). The handler in memoir-service enforces a soft cap on
    /// very large values — agents typically request 5-50. No cursor-based
    /// pagination in v0.1.
    #[prost(int32, tag="3")]
    pub limit: i32,
    /// Optional metadata filter — JSON-encoded Qdrant payload filter.
    /// Exact shape is implementation-defined and may evolve. NOTE: as of
    /// memoir-core v0.1 the library does not consume this field; handler
    /// implementations may return Unimplemented or drop it until the library
    /// gains a metadata-filter builder option.
    #[prost(message, optional, tag="4")]
    pub metadata_filter: ::core::option::Option<::pbjson_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResponse {
    #[prost(message, repeated, tag="1")]
    pub hits: ::prost::alloc::vec::Vec<SearchHit>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecallRequest {
    #[prost(string, tag="1")]
    pub pid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecallResponse {
    #[prost(message, optional, tag="1")]
    pub memory: ::core::option::Option<Memory>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RememberRequest {
    #[prost(message, optional, tag="1")]
    pub scope: ::core::option::Option<Scope>,
    #[prost(string, tag="2")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub metadata: ::core::option::Option<::pbjson_types::Struct>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RememberResponse {
    /// The persisted memory. `status` is always `MEMORY_STATUS_PENDING` at
    /// write time — the worker drains the embed (and, if configured, extract)
    /// queue asynchronously. Consumers needing job-state visibility use the
    /// `AdminService` (see `admin.proto`) rather than additional fields here.
    #[prost(message, optional, tag="1")]
    pub memory: ::core::option::Option<Memory>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgetRequest {
    /// When false, soft-delete (status preserved, memory excluded from search).
    #[prost(bool, tag="3")]
    pub hard_delete: bool,
    /// Either pid (target a single memory) OR scope (target every memory in a scope).
    /// Exactly one must be set.
    #[prost(oneof="forget_request::Target", tags="1, 2")]
    pub target: ::core::option::Option<forget_request::Target>,
}
/// Nested message and enum types in `ForgetRequest`.
pub mod forget_request {
    /// Either pid (target a single memory) OR scope (target every memory in a scope).
    /// Exactly one must be set.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Target {
        #[prost(string, tag="1")]
        Pid(::prost::alloc::string::String),
        #[prost(message, tag="2")]
        Scope(super::Scope),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgetResponse {
    /// The pids that were actually removed from the source of truth. Empty
    /// when the target matched no rows (not an error). Mirrors the library's
    /// `Client::forget` return shape (`Vec<String>`).
    #[prost(string, repeated, tag="1")]
    pub deleted_pids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MemoryStatus {
    Unspecified = 0,
    /// Written, not yet processed by the worker.
    Pending = 1,
    /// Extraction + embedding + graph update done.
    Processed = 2,
    /// Processing failed after max retries. See admin "failed writes" view.
    Failed = 3,
}
impl MemoryStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MEMORY_STATUS_UNSPECIFIED",
            Self::Pending => "MEMORY_STATUS_PENDING",
            Self::Processed => "MEMORY_STATUS_PROCESSED",
            Self::Failed => "MEMORY_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEMORY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MEMORY_STATUS_PENDING" => Some(Self::Pending),
            "MEMORY_STATUS_PROCESSED" => Some(Self::Processed),
            "MEMORY_STATUS_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
include!("memoir.v1.serde.rs");
include!("memoir.v1.tonic.rs");
// @@protoc_insertion_point(module)